// Spanish (Español). Keys are the English strings used in the app; anything missing shows in English.
// Covers the worker-facing flow: home, signing a card, the member page, the private record, safety.
// TODO(lawyer): have a bilingual attorney or a certified translator review every legal-facing string.
export default {
  // frame
  'Quick exit': 'Salida rápida',
  'Leave this page right now (or press Esc three times)': 'Salir de esta página ahora mismo (o presiona Esc tres veces)',
  'Project Ludlow is a tool. It is not a union and not a law firm.': 'Project Ludlow es una herramienta. No es un sindicato ni un bufete de abogados.',
  'How your data is protected': 'Cómo se protegen tus datos', 'Your rights': 'Tus derechos', 'Safety tips': 'Consejos de seguridad',
  'Verify this software': 'Verificar este software', 'Terms': 'Términos', 'Tab title': 'Título de la pestaña', 'Language': 'Idioma',
  'Copied': 'Copiado', 'Back': 'Atrás', 'Next': 'Siguiente', 'Cancel': 'Cancelar', 'Copy': 'Copiar', 'Delete': 'Eliminar', 'Confirm': 'Confirmar',
  'Share': 'Compartir', 'Copy link': 'Copiar enlace', 'Copy a message to send': 'Copiar un mensaje para enviar', 'Read aloud': 'Leer en voz alta',
  'Page not found': 'Página no encontrada', 'Go to the home page': 'Ir a la página de inicio', 'That did not work.': 'Eso no funcionó.',
  // home
  'Start a union at your workplace, safely.': 'Forma un sindicato en tu lugar de trabajo, de forma segura.',
  'Collect signed authorization cards that are locked so only your own committee can open them. Then run your union openly and fairly, with tools that let every member check the work.': 'Reúne tarjetas de autorización firmadas y cerradas con llave, para que solo tu propio comité pueda abrirlas. Luego dirige tu sindicato de forma abierta y justa, con herramientas que permiten a cada miembro comprobar el trabajo.',
  'Start a campaign': 'Empezar una campaña', 'Open my union workspace': 'Abrir el espacio de mi sindicato',
  'Got an invitation link from a coworker? Just open it. You do not need an account.': '¿Recibiste un enlace de invitación de un compañero? Solo ábrelo. No necesitas una cuenta.',
  'How it works': 'Cómo funciona',
  'A few trusted coworkers become trustees.': 'Unos pocos compañeros de confianza se convierten en custodios de las llaves.',
  'You can start alone and add them as you go. Until every trustee has joined and you have confirmed the committee, only you can open the cards. After that, any group of them, for example 3 of 5, can open the cards, and only after enough people have signed. No one alone can.': 'Puedes empezar solo y agregarlos poco a poco. Hasta que se hayan unido todos los custodios y tú hayas confirmado el comité, solo tú puedes abrir las tarjetas. Después, cualquier grupo de ellos, por ejemplo 3 de 5, podrá abrirlas, y solo cuando hayan firmado suficientes personas. Nadie puede hacerlo solo.',
  'Your card was not signed': 'Tu tarjeta no se firmó',
  'Stop.': 'Alto.',
  'Check who this is sealed to': 'Comprueba para quién está sellada',
  'Your card is sealed so that only the founder of this campaign (and, once they confirm it, the committee they name) can open it. These words identify the founder\'s key. To be sure, ask the founder to read theirs to you.': 'Tu tarjeta está sellada para que solo quien fundó esta campaña (y, cuando lo confirme, el comité que nombre) pueda abrirla. Estas palabras identifican su clave. Para estar seguro o segura, pídele que te lea las suyas.',
  "This invitation is from an older version, so it cannot check the trustees' keys. Ask whoever invited you for a new link.": 'Esta invitación es de una versión anterior, así que no puede comprobar las claves de los custodios. Pide un enlace nuevo a quien te invitó.',
  'The founder has not set up their key yet. Please try again later.': 'Quien fundó la campaña aún no ha creado su clave. Inténtalo de nuevo más tarde.',
  'The keys this website gave your phone do not match your invitation, so nothing was signed or sent. The website may have been tampered with, or the link may have been changed. Tell whoever invited you, in person or by phone, and do not try again from this link.': 'Las claves que este sitio dio a tu teléfono no coinciden con tu invitación, así que no se firmó ni se envió nada. Puede que alguien haya manipulado el sitio o que el enlace haya sido cambiado. Díselo en persona o por teléfono a quien te invitó, y no vuelvas a intentarlo con este enlace.',
  'The committee this website showed is not the one the founder signed, so nothing was signed or sent. The website may have been tampered with. Tell whoever invited you, in person or by phone.': 'El comité que mostró este sitio no es el que firmó quien fundó la campaña, así que no se firmó ni se envió nada. Puede que alguien haya manipulado el sitio. Díselo en persona o por teléfono a quien te invitó.',
  'The committee this website lists does not match the roster that was signed, so nothing was signed or sent. If you were invited to sign a card, the website may have been tampered with: tell whoever invited you, in person or by phone. If you are trustee 1, look again and check your key words.': 'El comité que muestra este sitio no coincide con la lista firmada, así que no se firmó ni se envió nada. Si te invitaron a firmar una tarjeta, puede que alguien haya manipulado el sitio: díselo en persona o por teléfono a quien te invitó. Si eres el custodio 1, mira de nuevo y comprueba tus palabras clave.',
  'Your card stays sealed. Until at least {n} people have signed and been counted, nobody can open it: not the trustees, and not this website.': 'Tu tarjeta permanece sellada. Hasta que al menos {n} personas hayan firmado y sido contadas, nadie puede abrirla: ni los custodios, ni este sitio web.',
  'Coworkers sign on their own phones.': 'Los compañeros firman en sus propios teléfonos.',
  'Each card is locked on the phone before it is sent. This website stores only scrambled data.': 'Cada tarjeta se cifra en el teléfono antes de enviarse. Este sitio web solo guarda datos codificados.',
  'You decide when to go public.': 'Ustedes deciden cuándo hacerlo público.',
  'When you have enough support, the trustees open the cards together and get a package to review: a roster, the cards, and draft letters and forms.': 'Cuando tengan suficiente apoyo, los custodios abren las tarjetas juntos y reciben un paquete para revisar: una lista, las tarjetas y borradores de cartas y formularios.',
  'Then run the union in the open.': 'Luego dirijan el sindicato con transparencia.',
  'Votes, money and workplace cases, built so that every member can check that they were done fairly.': 'Votaciones, dinero y casos laborales, diseñados para que cada miembro pueda comprobar que se hicieron con justicia.',
  'Built so you do not have to trust us': 'Diseñado para que no tengas que confiar en nosotros',
  'Cards are encrypted in the browser, and this website holds no key that opens them. It sees a signer\'s details only once, to send the confirmation email the law requires, and then discards them.': 'Las tarjetas se cifran en el navegador y este sitio web no tiene ninguna llave para abrirlas. Solo ve los datos de quien firma una vez, para enviar el correo de confirmación que exige la ley, y luego los borra.',
  'Votes are secret. When the committee publishes the ballot key (always, for decisions the system carries out), every member can recount the ballots themselves.': 'Los votos son secretos. Cuando el comité publica la llave de las papeletas (siempre, en las decisiones que el sistema aplica por sí mismo), cada miembro puede volver a contar las papeletas.',
  "The union's books are a chain that cannot be quietly edited. Your browser checks it.": 'Las cuentas del sindicato forman una cadena que no se puede editar en silencio. Tu navegador la comprueba.',
  'Spending needs two officers. Members can force a vote or a recall by petition.': 'Los gastos necesitan a dos dirigentes. Los miembros pueden exigir una votación o una destitución con una petición.',
  'You can run your own copy of the server and export everything at any time.': 'Puedes ejecutar tu propia copia del servidor y exportar todo en cualquier momento.',
  'This is a tool.': 'Esto es una herramienta.',
  'It is not a union and not a law firm. It never files anything or contacts your employer for you. Everything it produces is a draft for people to review.': 'No es un sindicato ni un bufete de abogados. Nunca presenta nada ni contacta a tu empleador por ti. Todo lo que produce es un borrador para que lo revisen personas.',
  // signing
  'This link is incomplete. Ask for it to be sent again, and make sure the whole link is copied.': 'Este enlace está incompleto. Pide que te lo envíen de nuevo y asegúrate de copiar el enlace completo.',
  'This invitation is no longer valid. It may have expired, been used, or been withdrawn. Ask the person who sent it for a new one.': 'Esta invitación ya no es válida. Puede haber caducado, haberse usado o haberse retirado. Pídele a quien te la envió una nueva.',
  'Coworkers at {employer} are forming a union, and you have been invited to sign an authorization card.': 'Compañeros de {employer} están formando un sindicato y te han invitado a firmar una tarjeta de autorización.',
  'Your information is encrypted on your phone before it is sent. This website cannot read it.': 'Tu información se cifra en tu teléfono antes de enviarse. Este sitio web no puede leerla.',
  'Before you sign': 'Antes de firmar',
  'Use your own phone, on your mobile data, and not at work.': 'Usa tu propio teléfono, con tus datos móviles, y no en el trabajo.',
  'Signing is your choice. Nobody can make you.': 'Firmar es decisión tuya. Nadie puede obligarte.',
  'You will get a confirmation email. If you did not sign, you can tell us.': 'Recibirás un correo de confirmación. Si no firmaste, puedes avisarnos.',
  'The law protects your right to organize.': 'La ley protege tu derecho a organizarte.',
  'Read about your rights': 'Lee sobre tus derechos', 'Read the card': 'Leer la tarjeta', 'Your authorization card': 'Tu tarjeta de autorización', 'Card language': 'Idioma de la tarjeta',
  'Signature (type your name below)': 'Firma (escribe tu nombre abajo)', 'Date: recorded by the server when you sign.': 'Fecha: la registra el servidor cuando firmas.',
  "Encrypted on your device. This site can't read it.": 'Cifrado en tu dispositivo. Este sitio no puede leerlo.',
  'Full legal name': 'Nombre legal completo', 'Personal email': 'Correo electrónico personal',
  'Not your work email. We send a confirmation here, as the law requires.': 'No tu correo del trabajo. Aquí enviamos una confirmación, como exige la ley.',
  'Mobile phone': 'Teléfono móvil', 'Optional details': 'Detalles opcionales', 'Job title': 'Puesto', 'Shift or department': 'Turno o departamento', 'Preferred language': 'Idioma preferido',
  'Please do not enter your date of birth, Social Security number or any ID number.': 'Por favor no escribas tu fecha de nacimiento, número de Seguro Social ni ningún número de identificación.',
  'Type your full name to sign': 'Escribe tu nombre completo para firmar', 'I have read the card above and I agree to it.': 'He leído la tarjeta de arriba y estoy de acuerdo.', 'Sign the card': 'Firmar la tarjeta',
  'Please enter your full legal name.': 'Por favor escribe tu nombre legal completo.', 'Please enter a valid personal email address.': 'Por favor escribe un correo electrónico personal válido.',
  'Please enter a phone number with 10 digits.': 'Por favor escribe un número de teléfono de 10 dígitos.',
  'Please do not enter dates of birth, Social Security numbers or ID numbers. They are not needed and must not be included.': 'Por favor no escribas fechas de nacimiento, números de Seguro Social ni de identificación. No son necesarios y no deben incluirse.',
  'Type your full name exactly as above to sign.': 'Escribe tu nombre completo exactamente como arriba para firmar.', 'Please check the box to agree to the card.': 'Por favor marca la casilla para aceptar la tarjeta.',
  'Almost done': 'Casi listo', 'Your card is signed and counted': 'Tu tarjeta está firmada y contada',
  'Tell this code, in person, to the coworker who invited you:': 'Dile este código, en persona, al compañero que te invitó:',
  'Your card counts once they enter it. Do not send it in a message.': 'Tu tarjeta cuenta cuando él o ella lo ingrese. No lo envíes por mensaje.',
  'Thank you. Your card is counted.': 'Gracias. Tu tarjeta está contada.',
  'We sent a confirmation email to {email}. If you did not sign, the email has a link to tell us.': 'Enviamos un correo de confirmación a {email}. Si no firmaste, el correo tiene un enlace para avisarnos.',
  'Your card is saved, but we could not send the confirmation email.': 'Tu tarjeta está guardada, pero no pudimos enviar el correo de confirmación.', 'Try again': 'Intentar de nuevo',
  'Save your member link': 'Guarda tu enlace de miembro',
  'This link is how you come back to see progress, invite others, and keep your private record. Anyone who has it can act as you, so keep it private, for example in a password manager or a Signal "Note to Self". Nobody, including us, can recover it for you.': 'Con este enlace vuelves para ver el progreso, invitar a otros y llevar tu registro privado. Cualquiera que lo tenga puede actuar como tú, así que guárdalo en privado, por ejemplo en un gestor de contraseñas o en las "Notas para mí" de Signal. Nadie, ni nosotros, puede recuperarlo por ti.',
  'Copy my link': 'Copiar mi enlace', 'Share it to myself': 'Enviármelo a mí', 'Open my page': 'Abrir mi página', 'What happens next': 'Qué sigue',
  'Your coworkers may invite you to help. You decide.': 'Tus compañeros pueden invitarte a ayudar. Tú decides.',
  'Nothing is sent to your employer. The trustees decide together when to go public.': 'No se envía nada a tu empleador. Los custodios deciden juntos cuándo hacerlo público.',
  'If your employer asks about the union, you never have to answer, and you can write it down privately on your member page.': 'Si tu empleador te pregunta por el sindicato, nunca tienes que responder, y puedes anotarlo en privado en tu página de miembro.',
  // member page
  'No card on this device': 'No hay ninguna tarjeta en este dispositivo',
  'Where we are': 'Dónde estamos', 'of about {size} coworkers have signed ({p})': 'de unos {size} compañeros han firmado ({p})', 'Cards signed': 'Tarjetas firmadas',
  'You are signed on at {employer}. Thank you.': 'Ya firmaste en {employer}. Gracias.', 'Bring in a coworker': 'Trae a un compañero',
  'Invite people you know and trust, one at a time. Do it in person or through an app you trust.': 'Invita a personas que conozcas y en quienes confíes, una por una. Hazlo en persona o con una aplicación de confianza.',
  'Invite one person': 'Invitar a una persona', 'Create a group link': 'Crear un enlace de grupo',
  'Hi, some of us at {employer} are forming a union. Please sign a card with this link, on your own phone and not at work: ': 'Hola, algunos de nosotros en {employer} estamos formando un sindicato. Por favor firma una tarjeta con este enlace, en tu propio teléfono y no en el trabajo: ',
  'Anyone who gets this link can sign, but their card will not count until you confirm them in person.': 'Cualquiera que reciba este enlace puede firmar, pero su tarjeta no contará hasta que lo confirmes en persona.',
  'People waiting for you to confirm': 'Personas esperando tu confirmación',
  'Ask each person for the two-word code they were shown. Only enter it if you met them in person.': 'Pídele a cada persona el código de dos palabras que vio. Solo ingrésalo si la conociste en persona.',
  'Confirmed. Their card now counts.': 'Confirmado. Su tarjeta ya cuenta.', 'That code is not right. {n} tries left.': 'Ese código no es correcto. Quedan {n} intentos.',
  'One more is waiting to be confirmed in person.': 'Falta una persona por confirmar en persona.', '{n} more are waiting to be confirmed in person.': 'Faltan {n} personas por confirmar en persona.',
  'Show QR code': 'Mostrar código QR', 'Hide QR code': 'Ocultar código QR', 'Show this only to the person you are inviting.': 'Muéstralo solo a la persona que estás invitando.',
  'Withdraw my card': 'Retirar mi tarjeta', 'Your card was deleted.': 'Tu tarjeta fue eliminada.',
  'Withdraw your card? It is permanently deleted from the server and no longer counts. This cannot be undone.': '¿Retirar tu tarjeta? Se elimina para siempre del servidor y deja de contar. No se puede deshacer.',
  'Your card is waiting to be confirmed by the coworker who invited you.': 'Tu tarjeta está esperando ser confirmada por el compañero que te invitó.', 'Tell them this code, in person:': 'Dile este código, en persona:',
  'Once they confirm you, your card counts and you will see progress here. Nothing else is needed from you.': 'Cuando te confirme, tu tarjeta contará y verás el progreso aquí. No se necesita nada más de ti.',
  'Your member link': 'Tu enlace de miembro', 'Keep it private. It is how you get back here.': 'Mantenlo en privado. Es la forma de volver aquí.',
  'The trustees have paused this campaign. No new cards can be signed for now.': 'Los custodios pausaron esta campaña. Por ahora no se pueden firmar tarjetas nuevas.',
  // private record
  'My private record': 'Mi registro privado',
  'Write down anything that looks like punishment for organizing. Only you can read it. Not the trustees, not this website, unless you choose to share an entry.': 'Anota todo lo que parezca un castigo por organizarse. Solo tú puedes leerlo. Ni los custodios ni este sitio web, a menos que decidas compartir una entrada.',
  'Add something that happened': 'Agregar algo que pasó', 'What happened?': '¿Qué pasó?', 'Date': 'Fecha', 'What was said or done?': '¿Qué se dijo o se hizo?',
  'Write what you saw and heard, in your own words. Facts, not opinions.': 'Escribe lo que viste y oíste, con tus propias palabras. Hechos, no opiniones.',
  'Who was involved?': '¿Quién estuvo involucrado?', 'Who else saw it?': '¿Quién más lo vio?', 'Save privately': 'Guardar en privado', 'Please describe what happened.': 'Por favor describe lo que pasó.',
  'Asked whether I or others support the union': 'Me preguntaron si yo u otros apoyamos al sindicato', 'Threatened me or others': 'Me amenazaron a mí o a otros',
  'Promised a benefit to drop the union': 'Prometieron un beneficio para que abandonara el sindicato', 'Watched or followed union activity': 'Vigilaron o siguieron la actividad sindical',
  'Disciplined, fired or cut my hours': 'Me sancionaron, despidieron o redujeron mis horas', 'Required me to attend an anti-union meeting': 'Me obligaron a asistir a una reunión contra el sindicato', 'Something else': 'Otra cosa',
  'Share with the committee': 'Compartir con el comité', 'Shared with the committee.': 'Compartido con el comité.', 'Download my record': 'Descargar mi registro',
  'Time limit to file a charge: about {n} days left': 'Plazo para presentar una queja: quedan unos {n} días', 'Deadline to file may have passed. Ask soon.': 'Es posible que el plazo haya pasado. Consulta pronto.',
  'Time limits are general guidance, not legal advice. A lawyer or the labor board can tell you the exact deadline.': 'Los plazos son orientación general, no asesoría legal. Un abogado o la junta laboral pueden decirte el plazo exacto.',
  // trustee enrollment (most important screens)
  'Become a trustee for {union}': 'Conviértete en custodio de {union}',
  '1. Choose a passphrase': '1. Elige una frase de acceso', '2. Create and save your key file': '2. Crea y guarda tu archivo de llave', '3. Finish': '3. Terminar',
  'Create my key file': 'Crear mi archivo de llave', 'Finish enrollment': 'Terminar la inscripción', 'You are enrolled': 'Estás inscrito',
  'I saved my key file and my passphrase somewhere safe.': 'Guardé mi archivo de llave y mi frase de acceso en un lugar seguro.',
  // wizard
  'Where do you work?': '¿Dónde trabajas?', 'What will your union be called?': '¿Cómo se llamará tu sindicato?', 'Union name': 'Nombre del sindicato',
  'Who is your employer?': '¿Quién es tu empleador?', "Employer's legal name": 'Nombre legal del empleador', 'Who is in your group?': '¿Quiénes están en tu grupo?',
  'About how many people is that?': '¿Aproximadamente cuántas personas son?', 'Number of coworkers': 'Número de compañeros',
  'Create my campaign': 'Crear mi campaña', 'Your campaign is ready': 'Tu campaña está lista', 'Step {i} of {n}': 'Paso {i} de {n}',
  'Read the card your coworkers will sign': 'Lee la tarjeta que firmarán tus compañeros',
  // safety
  'Sign in': 'Iniciar sesión',
  // error messages (api.js FRIENDLY, shown through t(friendly(e))) (first draft, needs a native reviewer: #10)
  'You seem to be offline. Check your connection and try again.': 'Parece que no tienes conexión. Revisa tu conexión e inténtalo de nuevo.',
  'Too many tries. Wait a minute and try again.': 'Demasiados intentos. Espera un minuto e inténtalo de nuevo.',
  'That link, key or sign-in is not valid any more.': 'Ese enlace, llave o inicio de sesión ya no es válido.',
  'Your session ended. Please sign in again.': 'Tu sesión terminó. Por favor inicia sesión de nuevo.',
  'You do not have permission to do that.': 'No tienes permiso para hacer eso.',
  'That could not be found.': 'No se encontró.',
  'This invitation link is no longer valid. Ask for a new one.': 'Este enlace de invitación ya no es válido. Pide uno nuevo.',
  'This campaign is not accepting cards right now.': 'Esta campaña no está aceptando tarjetas en este momento.',
  'That code is not right.': 'Ese código no es correcto.',
  'Too many wrong codes. This card is locked.': 'Demasiados códigos incorrectos. Esta tarjeta está bloqueada.',
  'You have already voted.': 'Ya votaste.',
  'This vote is closed.': 'Esta votación está cerrada.',
  'This is only available once your union is recognized.': 'Esto solo está disponible cuando tu sindicato esté reconocido.',
  'No chief steward has set up an account yet, so nobody could read this. Ask an officer to assign one.': 'Ningún delegado principal ha creado su cuenta todavía, así que nadie podría leer esto. Pide a un dirigente que asigne uno.',
  'You cannot approve your own request.': 'No puedes aprobar tu propia solicitud.',
  'That has already been done.': 'Eso ya se hizo.',
  'Candidates cannot sit on the committee that runs their own election.': 'Los candidatos no pueden formar parte del comité que organiza su propia elección.',
  'This feature is turned off until your attorney approves it.': 'Esta función está desactivada hasta que tu abogado la apruebe.',
  'We could not send the confirmation email.': 'No pudimos enviar el correo de confirmación.',
  'There must be at least one officer.': 'Debe haber al menos un dirigente.',
  'The cards stay locked until enough people have signed.': 'Las tarjetas siguen cerradas hasta que hayan firmado suficientes personas.',
  'The committee just changed. Please try again.': 'El comité acaba de cambiar. Por favor inténtalo de nuevo.',
  'Only the founder (trustee 1) can do that.': 'Solo quien fundó la campaña (el custodio 1) puede hacer eso.',
  'This link is missing part of its key. Ask for it to be sent again and copy the whole link.': 'A este enlace le falta parte de su llave. Pide que te lo envíen de nuevo y copia el enlace completo.',
  'Not every trustee has joined yet.': 'Todavía no se han unido todos los custodios.',
  'The website says a different number of trustees, or a different number needed together, than you chose. Nothing was signed. Look at the plan again before you confirm: something may be wrong.': 'El sitio web indica un número de custodios, o un número necesario en conjunto, distinto del que elegiste. No se firmó nada. Revisa el plan otra vez antes de confirmar: puede que algo esté mal.',
  'This invitation is for a trustee, but the website put you in the founder\'s seat. Nothing was set up. Tell trustee 1 in person or by phone.': 'Esta invitación es para un custodio, pero el sitio web te puso en el lugar de quien fundó la campaña. No se configuró nada. Díselo al custodio 1 en persona o por teléfono.',
  'The website put a key in your own seat that is not yours. Do not confirm the committee: something is wrong. Tell the other trustees.': 'El sitio web puso en tu propio lugar una llave que no es tuya. No confirmes el comité: algo está mal. Avísales a los demás custodios.',
  'The committee the founder signed does not contain your key. Talk to trustee 1 before you trust this campaign.': 'El comité que firmó quien fundó la campaña no contiene tu llave. Habla con el custodio 1 antes de confiar en esta campaña.',
  'The founder has not confirmed the committee yet.': 'Quien fundó la campaña aún no ha confirmado el comité.',
  'The committee has already been confirmed.': 'El comité ya fue confirmado.',
  'That confirmation could not be checked. Please try again.': 'No se pudo comprobar esa confirmación. Por favor inténtalo de nuevo.',
  'Something went wrong. Please try again.': 'Algo salió mal. Por favor inténtalo de nuevo.',
  // shared helpers (ui.js) (first draft, needs a native reviewer: #10)
  'just now': 'ahora mismo',
  '{n} min ago': 'hace {n} min',
  '{n} hours ago': 'hace {n} horas',
  '{n} days ago': 'hace {n} días',
  'Could not copy. Select the text and copy it yourself.': 'No se pudo copiar. Selecciona el texto y cópialo tú.',
  'Reading aloud is not available on this device.': 'La lectura en voz alta no está disponible en este dispositivo.',
  'The tab now shows the app name.': 'La pestaña ahora muestra el nombre de la aplicación.',
  'The tab now says "Notes" on private pages.': 'La pestaña ahora dice "Notes" en las páginas privadas.',
  // workspace frame (wsbase.js) (first draft, needs a native reviewer: #10)
  'Sign in to your workspace': 'Inicia sesión en tu espacio',
  'Your workspace is protected by your key file and passphrase.': 'Tu espacio está protegido con tu archivo de llave y tu frase de acceso.',
  'Workspace': 'Espacio del sindicato',
  'Recognized': 'Reconocido',
  'Lock': 'Bloquear',
  'Overdue by {n} days': 'Vencido hace {n} días',
  'Due today': 'Vence hoy',
  'Due in {n} days': 'Vence en {n} días',
  'Home': 'Inicio',
  'Union': 'Sindicato',
  // rule settings (shared/constants.js POLICY_FIELDS labels) (first draft, needs a native reviewer: #10)
  'Members needed to force a vote (percent of members)': 'Miembros necesarios para exigir una votación (porcentaje de los miembros)',
  'Members needed to force a recall vote (percent of members)': 'Miembros necesarios para exigir una votación de destitución (porcentaje de los miembros)',
  'Spending at or above this needs two officers to approve (cents)': 'Los gastos de esta cantidad o más necesitan la aprobación de dos dirigentes (centavos)',
  'Officer term length (months)': 'Duración del mandato de los dirigentes (meses)',
  // progress-bar markers (packs.js) (first draft, needs a native reviewer: #10)
  '30%: enough to ask the NLRB for an election': '30%: suficiente para pedir una elección a la NLRB',
  '50% + 1: a majority': '50% + 1: una mayoría',
  '70%: a safe cushion before you go public': '70%: un margen seguro antes de hacerlo público',
  '10%: the minimum membership to apply to the CAC (this may be lowered)': '10%: la afiliación mínima para presentar una solicitud al CAC (puede reducirse)',
  '50% + 1: more than half; the CAC can usually recognise without a ballot': '50% + 1: más de la mitad; el CAC normalmente puede otorgar el reconocimiento sin votación',
  // verify page (pages.js) (first draft, needs a native reviewer: #10)
  'Working...': 'Procesando...',
  'Paste the published fingerprint here': 'Pega aquí la huella digital publicada',
  'Paste a fingerprint first.': 'Primero pega una huella digital.',
  'Match: this is the software that was published.': 'Coinciden: este es el software que se publicó.',
  'They do NOT match. Do not enter any private information.': 'NO coinciden. No ingreses ninguna información privada.',
  'The code running in your browser has this SHA-256 fingerprint:': 'El código que se ejecuta en tu navegador tiene esta huella digital SHA-256:',
  'Version {v}': 'Versión {v}',
  'Could not read the software to check it.': 'No se pudo leer el software para comprobarlo.',
  'The biggest risk in any web app is a server that quietly sends you different code. You can protect yourself by comparing the fingerprint of the code you are running with the one published for the release, and by comparing with your fellow trustees before you open cards.': 'El mayor riesgo de cualquier aplicación web es un servidor que, sin avisar, te envía un código distinto. Puedes protegerte comparando la huella digital del código que estás ejecutando con la publicada para esa versión, y comparándola con los demás custodios antes de abrir las tarjetas.',
  'Published fingerprint': 'Huella digital publicada',
  'Compare': 'Comparar',
  'Honest limits: this page downloads the code again to work out its fingerprint. A server determined to cheat could show this page one file and run another, or show different code to different people. So this is a check against mistakes and casual tampering, not against a hostile server. The strongest check is to compare with a fingerprint you built yourself from the source, or one that someone you trust worked out on another device and network. That is also why you can run your own copy of the server.': 'Límites, con honestidad: esta página vuelve a descargar el código para calcular su huella digital. Un servidor decidido a hacer trampa podría mostrarle a esta página un archivo y ejecutar otro, o mostrar un código distinto a cada persona. Así que esto protege contra errores y manipulaciones casuales, no contra un servidor hostil. La comprobación más fuerte es comparar con una huella digital que tú mismo generaste a partir del código fuente, o con una que calculó alguien de tu confianza en otro dispositivo y otra red. Por eso también puedes ejecutar tu propia copia del servidor.',
  // starting the workspace (founding.js) (first draft, needs a native reviewer: #10)
  'Choose at least one officer from the roster.': 'Elige al menos un dirigente de la lista.',
  'Each officer must be a different person.': 'Cada dirigente debe ser una persona distinta.',
  'Start your union workspace': 'Crea el espacio de tu sindicato',
  'A union that has gone public needs a real membership list to hold votes, collect dues and represent people by name. The workspace does that.': 'Un sindicato que ya se hizo público necesita una lista real de miembros para hacer votaciones, cobrar cuotas y representar a las personas por su nombre. El espacio del sindicato hace eso.',
  'Read this before you continue.': 'Lee esto antes de continuar.',
  'Creating a workspace copies the names, emails and phone numbers of {n} signers to the server, where officers can see them. They are encrypted at rest, but they are no longer secret. Only do this once your union has already gone public: you have sent a demand letter or filed a petition.': 'Crear el espacio copia al servidor los nombres, correos y teléfonos de {n} firmantes, donde los dirigentes pueden verlos. Se guardan cifrados, pero ya no son secretos. Hazlo solo cuando tu sindicato ya se haya hecho público: cuando hayan enviado una carta de exigencia o presentado una petición.',
  'We have already gone public.': 'Ya nos hicimos públicos.',
  'Where is your union right now?': '¿En qué etapa está tu sindicato ahora?',
  'Public, not yet recognized': 'Público, aún no reconocido',
  'Recognized or certified': 'Reconocido o certificado',
  'Grievance handling and bargaining tools only turn on once you are recognized. You can change this later with a note.': 'Las herramientas de quejas formales y de negociación solo se activan cuando estén reconocidos. Puedes cambiar esto más adelante con una nota.',
  'Interim officers': 'Dirigentes provisionales',
  'Until your first election, your trustees can hold these roles. Choose who each trustee is on the roster. You can change roles later. Committee votes need at least two people on the election committee.': 'Hasta su primera elección, los custodios pueden ocupar estos cargos. Elige quién es cada custodio en la lista. Puedes cambiar los cargos más adelante. Las votaciones del comité necesitan al menos dos personas en el comité electoral.',
  'This trustee is': 'Este custodio es',
  '(not on the roster)': '(no está en la lista)',
  'Fiscal year starts (MM-DD)': 'Inicio del año fiscal (MM-DD)',
  'Time zone': 'Zona horaria',
  'Create the workspace': 'Crear el espacio',
  'Your workspace is ready': 'Tu espacio está listo',
  'Hi {name}, our union workspace is ready. Claim your account with this link, on your own phone: ': 'Hola {name}, el espacio de nuestro sindicato está listo. Activa tu cuenta con este enlace, en tu propio teléfono: ',
  'Each link below is a key to one person\'s account.': 'Cada enlace de abajo es la llave de la cuenta de una persona.',
  'Send each one privately to that person only. It works once. Then destroy the campaign so the old, anonymous data is deleted.': 'Envía cada uno en privado solo a esa persona. Funciona una sola vez. Luego destruye la campaña para que se borren los datos anteriores y anónimos.',
  'Download all links (CSV)': 'Descargar todos los enlaces (CSV)',
  'Copy all messages': 'Copiar todos los mensajes',
  'Person': 'Persona',
  'Copy message': 'Copiar mensaje',
  'Once you have handed out the links and at least one officer has claimed their account, go back to your trustee dashboard and destroy the campaign.': 'Cuando hayas repartido los enlaces y al menos un dirigente haya activado su cuenta, vuelve a tu panel de custodio y destruye la campaña.',
  'Officer': 'Dirigente',
  'Treasurer': 'Tesorero',
  'Chief steward': 'Delegado principal',
  'Election committee': 'Comité electoral',
  // campaign, signing and member page (organize.js) (first draft, needs a native reviewer: #10)
  '{n} people: the earliest the cards can be opened': '{n} personas: lo más pronto que se pueden abrir las tarjetas',
  'Cards signed over time': 'Tarjetas firmadas a lo largo del tiempo',
  'At the pace so far, about {d} more days to reach {p}. This is only a rough guess.': 'Al ritmo que llevan, faltan unos {d} días para llegar a {p}. Es solo un cálculo aproximado.',
  'QR code for the invitation link': 'Código QR del enlace de invitación',
  'Passphrase': 'Frase de acceso',
  'Choose a key file': 'Elige un archivo de llave',
  'Key file loaded.': 'Archivo de llave cargado.',
  'That is not a usable key file.': 'Ese no es un archivo de llave que se pueda usar.',
  'Unlock': 'Desbloquear',
  'Choose a key file first.': 'Primero elige un archivo de llave.',
  'That passphrase is not right.': 'Esa frase de acceso no es correcta.',
  'No key file is saved on this device.': 'No hay ningún archivo de llave guardado en este dispositivo.',
  'Or choose a key file from your device': 'O elige un archivo de llave de tu dispositivo',
  'Two things protect your key:': 'Dos cosas protegen tu llave:',
  'the key file, and the passphrase that unlocks it. Lose either one and the cards it guards can never be opened by you.': 'el archivo de llave y la frase de acceso que lo desbloquea. Si pierdes cualquiera de los dos, nunca podrás abrir las tarjetas que protege.',
  'Trustee {n}': 'Custodio {n}',
  'Please fill this in first.': 'Por favor llena esto primero.',
  '[your employer]': '[tu empleador]',
  '[your union]': '[tu sindicato]',
  'This sets the legal steps, the card wording and the goals shown on your progress bar.': 'Esto define los pasos legales, el texto de la tarjeta y las metas que se muestran en tu barra de progreso.',
  'You can start your own independent union, or organize with one that already exists. Use the name your coworkers will recognize.': 'Puedes formar tu propio sindicato independiente u organizarte con uno que ya existe. Usa el nombre que tus compañeros van a reconocer.',
  'e.g. Riverside Baristas United': 'p. ej., Baristas Unidos de Riverside',
  'Use the legal name if you can. Check your paystub or tax form.': 'Usa el nombre legal si puedes. Revisa tu talón de pago o tu formulario de impuestos.',
  'Address (optional)': 'Dirección (opcional)',
  'Describe the coworkers who would be in the union. People with similar jobs, skills, supervisors and location usually belong together. Supervisors and managers usually do not.': 'Describe a los compañeros que estarían en el sindicato. Las personas con trabajos, habilidades, supervisores y lugar de trabajo parecidos normalmente van juntas. Los supervisores y gerentes normalmente no.',
  'Who is included?': '¿Quiénes están incluidos?',
  'e.g. All baristas and shift leads at the Main Street location': 'p. ej., todos los baristas y jefes de turno de la sucursal de Main Street',
  'A rough number is fine. Your progress bar uses it.': 'Un número aproximado está bien. Tu barra de progreso lo usa.',
  'Legal threshold (optional)': 'Umbral legal (opcional)',
  'If you know what share of coworkers your local law needs (in percent), enter it. Ask a local union or lawyer.': 'Si sabes qué porcentaje de compañeros exige la ley de tu lugar, anótalo. Pregunta a un sindicato local o a un abogado.',
  'When should the cards be allowed to open?': '¿Cuándo se deberían poder abrir las tarjetas?',
  'This is a safety lock. Until at least this many people have signed and been counted, the cards stay sealed: nobody can open them, not even all your trustees together, and this website will not hand them over. It is a safety catch, not a guarantee: it counts the cards the system accepted, anyone who can invite people can add cards, and until every trustee has joined and you have confirmed the committee, you alone hold the key.': 'Este es un seguro. Hasta que al menos esta cantidad de personas haya firmado y sido contada, las tarjetas permanecen selladas: nadie puede abrirlas, ni siquiera todos tus custodios juntos, y este sitio web no las entregará. Es un seguro, no una garantía: cuenta las tarjetas que el sistema aceptó, cualquiera que pueda invitar personas puede agregar tarjetas, y hasta que se hayan unido todos los custodios y tú hayas confirmado el comité, solo tú tienes la llave.',
  '{n} people': '{n} personas',
  'Or choose your own number': 'O elige tu propio número',
  'That is more than the {n} people you said are in your group. The cards would stay locked until more than everyone has signed.': 'Eso es más que las {n} personas que dijiste que hay en tu grupo. Las tarjetas seguirían cerradas hasta que firmaran más personas de las que hay.',
  'Trustees can raise this number later on their own. Lowering it takes several of them agreeing.': 'Cualquier custodio puede subir este número más adelante por su cuenta. Para bajarlo, tienen que estar de acuerdo varios de ellos.',
  'Your committee of trustees': 'Tu comité de custodios',
  'You can start with just yourself.': 'Puedes empezar tú solo.',
  'You will be able to invite coworkers as soon as you have made your key. Add the other trustees whenever they are ready.': 'Podrás invitar a tus compañeros en cuanto hayas creado tu llave. Agrega a los demás custodios cuando estén listos.',
  'Trustees are trusted coworkers who hold the keys. Once every trustee has joined and you have confirmed the committee, any {k} of the {n} together can open the cards (once the number above is reached). After that, no one can alone, and neither can this website.': 'Los custodios son compañeros de confianza que guardan las llaves. Cuando se hayan unido todos los custodios y tú hayas confirmado el comité, cualquier grupo de {k} de los {n} podrá abrir las tarjetas en conjunto (cuando se alcance el número de arriba). Desde entonces, nadie puede hacerlo solo, y este sitio web tampoco.',
  'Until every trustee has joined and you have confirmed the committee, only you can open the cards. That is fine for the first days, but add trustees soon, and keep your key file safe: it is the only way to open the cards until then, and it still opens any copy of the early cards made before you lock them to the committee.': 'Hasta que se hayan unido todos los custodios y tú hayas confirmado el comité, solo tú puedes abrir las tarjetas. Eso está bien para los primeros días, pero agrega custodios pronto y guarda bien tu archivo de llave: es la única forma de abrir las tarjetas hasta entonces, y seguirá abriendo cualquier copia de las primeras tarjetas hecha antes de que las cierres para el comité.',
  'How many trustees do you plan to have?': '¿Cuántos custodios piensas tener?',
  '3 trustees (recommended)': '3 custodios (recomendado)',
  '5 trustees': '5 custodios',
  'How many must be together to open the cards?': '¿Cuántos tienen que estar juntos para abrir las tarjetas?',
  '{k} of {n}': '{k} de {n}',
  'A majority of your trustees is a good choice. You can change this plan later.': 'Una mayoría de tus custodios es una buena opción. Puedes cambiar este plan más adelante.',
  'Your first name or nickname': 'Tu nombre o apodo',
  'Trustee {n}: first name or nickname (optional)': 'Custodio {n}: nombre o apodo (opcional)',
  'This is the exact wording. It is a draft that a labor attorney should review before you use it.': 'Este es el texto exacto. Es un borrador que un abogado laboral debe revisar antes de que lo uses.',
  'Your union name, employer and group are encrypted here on your device before anything is sent. The website will not be able to read them.': 'El nombre de tu sindicato, tu empleador y tu grupo se cifran aquí en tu dispositivo antes de enviar nada. El sitio web no podrá leerlos.',
  'Next, make your key. As soon as you have, you can invite coworkers to sign. You do not have to wait for anyone else.': 'Ahora crea tu llave. En cuanto la tengas, podrás invitar a tus compañeros a firmar. No tienes que esperar a nadie más.',
  'Trustee 1: {name} (you)': 'Custodio 1: {name} (tú)',
  'Your key file is the only way to open the cards until other trustees join. Guard it.': 'Tu archivo de llave es la única forma de abrir las tarjetas hasta que se unan otros custodios. Cuídalo.',
  'Set up my key': 'Crear mi llave',
  'Once your key is set up, invite your other trustees from your dashboard. Their invitations carry a check of your key, so that everyone who signs can make sure they are sealing to the real committee.': 'Cuando tengas tu llave, invita a los demás custodios desde tu panel. Sus invitaciones llevan una comprobación de tu llave, para que todos los que firmen puedan asegurarse de que están sellando su tarjeta para el comité verdadero.',
  'Hi {name}, I would like you to be a trustee for our union campaign at {employer}. Open this link on your personal phone and follow the steps: ': 'Hola {name}, me gustaría que fueras custodio de nuestra campaña sindical en {employer}. Abre este enlace en tu teléfono personal y sigue los pasos: ',
  'This link was already used': 'Este enlace ya se usó',
  'If you already set up your key, go to your trustee dashboard.': 'Si ya creaste tu llave, ve a tu panel de custodio.',
  'Trustee dashboard': 'Panel de custodio',
  'This invitation does not check out': 'Esta invitación no pasa la comprobación',
  '{x} of {n} trustees have set up their keys.': '{x} de {n} custodios han creado su llave.',
  'Your key words': 'Tus palabras clave',
  'Read these to trustee 1 by phone or in person. They check them before the cards are locked to the committee, so nobody can slip in a different key.': 'Léeselas al custodio 1 por teléfono o en persona. Las comprobará antes de cerrar las tarjetas para el comité, para que nadie pueda colar una llave distinta.',
  'Everyone has joined. Trustee 1 now checks each trustee\'s key words with them and confirms the committee. After that, any {k} of the {n} trustees together can open the cards.': 'Ya se unieron todos. Ahora el custodio 1 comprueba con cada custodio sus palabras clave y confirma el comité. Después, cualquier grupo de {k} de los {n} custodios podrá abrir las tarjetas en conjunto.',
  'You can start inviting coworkers now.': 'Ya puedes empezar a invitar a tus compañeros.',
  'Until every trustee has joined and you have confirmed the committee, only you can open the cards. Add trustees from your dashboard when they are ready.': 'Hasta que se hayan unido todos los custodios y tú hayas confirmado el comité, solo tú puedes abrir las tarjetas. Agrega custodios desde tu panel cuando estén listos.',
  'Thank you. Trustee 1 will confirm the committee, and lock the early cards to it, once everyone has joined.': 'Gracias. El custodio 1 confirmará el comité, y cerrará para él las primeras tarjetas, cuando todos se hayan unido.',
  'Go to my trustee dashboard': 'Ir a mi panel de custodio',
  'You hold one of {n} keys. Once everyone has joined and trustee 1 has confirmed the committee, any {k} of the trustees together can open the signed cards, and nobody can do it alone, including this website. Until then, trustee 1 alone can open them.': 'Tienes una de {n} llaves. Cuando todos se hayan unido y el custodio 1 haya confirmado el comité, cualquier grupo de {k} custodios podrá abrir en conjunto las tarjetas firmadas, y nadie podrá hacerlo solo, ni siquiera este sitio web. Hasta entonces, solo el custodio 1 puede abrirlas.',
  'You are trustee {i}{name}.': 'Eres el custodio {i}{name}.',
  'This invitation is from an older version and has no check of the founder\'s key, so this device will not be able to verify the committee. You can still be a trustee.': 'Esta invitación es de una versión anterior y no incluye la comprobación de la llave de quien fundó la campaña, así que este dispositivo no podrá verificar el comité. Aun así puedes ser custodio.',
  'You are the founder.': 'Tú fundaste la campaña.',
  'Until the other trustees join, this key file is the only way to open the cards. Back it up somewhere safe as well.': 'Hasta que se unan los demás custodios, este archivo de llave es la única forma de abrir las tarjetas. Guarda también una copia de respaldo en un lugar seguro.',
  'Your passphrase (at least 14 characters)': 'Tu frase de acceso (al menos 14 caracteres)',
  'Use a generated one instead': 'Usar una generada automáticamente',
  'Another one': 'Otra',
  'I will choose my own': 'Elegiré la mía',
  'Write the generated passphrase down or save it in a password manager.': 'Anota la frase de acceso generada o guárdala en un administrador de contraseñas.',
  'Download the key file again': 'Descargar el archivo de llave otra vez',
  'Your passphrase must be at least 14 characters and not a simple pattern (the same letters or words again, or a run like 12345). The generated one is best.': 'Tu frase de acceso debe tener al menos 14 caracteres y no ser un patrón simple (las mismas letras o palabras repetidas, o una serie como 12345). La generada es la mejor opción.',
  'Key file created and downloaded. A copy is also saved in this browser, but it still needs your passphrase.': 'Archivo de llave creado y descargado. También se guardó una copia en este navegador, pero igual necesita tu frase de acceso.',
  'Please confirm you saved your key file and passphrase.': 'Por favor confirma que guardaste tu archivo de llave y tu frase de acceso.',
  '{union}': '{union}',
  'Please enter your phone number with the country code, like +44 7700 900123.': 'Por favor escribe tu número de teléfono con el código de país, por ejemplo +44 7700 900123.',
  'My member link (keep private):': 'Mi enlace de miembro (mantenlo en privado):',
  'Testing on your own computer: ': 'Si estás haciendo pruebas en tu propia computadora: ',
  'open the test outbox': 'abre la bandeja de salida de prueba',
  'Open the member link you saved when you signed. If you lost it, ask the person who invited you to send a new invitation.': 'Abre el enlace de miembro que guardaste cuando firmaste. Si lo perdiste, pide a la persona que te invitó que te envíe una nueva invitación.',
  'This card no longer exists': 'Esta tarjeta ya no existe',
  'It may have been withdrawn or the campaign may have ended. Your data is gone from the server.': 'Puede que se haya retirado o que la campaña haya terminado. Tus datos ya no están en el servidor.',
  'The number is met, so the trustees can open the cards when they decide together to go public.': 'Ya se alcanzó el número, así que los custodios pueden abrir las tarjetas cuando decidan juntos hacerlo público.',
  'The cards stay sealed until {n} people have signed. Nobody can open them before then, not even the trustees together.': 'Las tarjetas permanecen selladas hasta que hayan firmado {n} personas. Nadie puede abrirlas antes, ni siquiera los custodios juntos.',
  'Forget this device': 'Olvidar este dispositivo',
  'Remove your saved sign-in from this device? To come back you will need the member link you saved. Nothing is deleted from the server.': '¿Quitar de este dispositivo tu inicio de sesión guardado? Para volver necesitarás el enlace de miembro que guardaste. No se borra nada del servidor.',
  'Code': 'Código',
  'Signer #{n}, {when}': 'Firmante n.º {n}, {when}',
  'Loading...': 'Cargando...',
  'This sends a copy to your trustees only. Any one of them can read it. It is not linked to your card. Add your name only if you want them to know it is you.': 'Esto envía una copia solo a tus custodios. Cualquiera de ellos puede leerla. No está vinculada a tu tarjeta. Agrega tu nombre solo si quieres que sepan que eres tú.',
  'Your name (optional)': 'Tu nombre (opcional)',
  'Involved: {x}': 'Involucrados: {x}',
  'Also saw it: {x}': 'También lo vieron: {x}',
  'Delete this entry for good?': '¿Eliminar esta entrada para siempre?',
  'Could not load your record.': 'No se pudo cargar tu registro.',
  'This link is incomplete.': 'Este enlace está incompleto.',
  'Thank you': 'Gracias',
  'We have recorded that you did not sign this card. It will be flagged for the organizers.': 'Registramos que no firmaste esta tarjeta. Quedará señalada para los organizadores.',
  'I did not sign this card': 'Yo no firmé esta tarjeta',
  'If you did not sign a union authorization card, tell us here. The card will be marked so it is not counted or used.': 'Si no firmaste una tarjeta de autorización sindical, avísanos aquí. La tarjeta se marcará para que no se cuente ni se use.',
  'If you did sign it and everything is fine, you can close this page.': 'Si sí la firmaste y todo está bien, puedes cerrar esta página.',
  // trustee dashboard and opening ceremony (trustee.js) (first draft, needs a native reviewer: #10)
  'Trustee {n} key file (campaign …{id})': 'Archivo de llave del custodio {n} (campaña …{id})',
  'Unlock your key file to continue. Your key never leaves this device.': 'Desbloquea tu archivo de llave para continuar. Tu llave nunca sale de este dispositivo.',
  'Active': 'Activa',
  'Paused': 'En pausa',
  'Setting up': 'En preparación',
  '{employer}. You are trustee {i}{name}. Any {k} of {n} trustees together can open the cards.': '{employer}. Eres el custodio {i}{name}. Cualquier grupo de {k} de los {n} custodios puede abrir las tarjetas en conjunto.',
  'This campaign has been quiet for a while. If nothing happens in {d} days it will be deleted automatically.': 'Esta campaña lleva un tiempo sin actividad. Si no pasa nada en {d} días, se borrará automáticamente.',
  'Waiting for trustees': 'Esperando a los custodios',
  'ready': 'listo',
  'has not set up a key yet': 'todavía no ha creado su llave',
  'Invite coworkers': 'Invitar a compañeros',
  'Cards waiting to be confirmed': 'Tarjetas esperando confirmación',
  'Enter the two-word code only if you have confirmed the person in person.': 'Escribe el código de dos palabras solo si confirmaste a la persona en persona.',
  'Open the cards': 'Abrir las tarjetas',
  'The cards are locked.': 'Las tarjetas están cerradas.',
  '{have} of the {need} people needed have signed and been counted. Until then nobody can open them, not even all the trustees together.': 'Han firmado y sido contadas {have} de las {need} personas necesarias. Hasta entonces nadie puede abrirlas, ni siquiera todos los custodios juntos.',
  'The number is met. When you decide together to go public, {k} trustees meet, ideally in person, and open the cards on one device.': 'Ya se alcanzó el número. Cuando decidan juntos hacerlo público, {k} custodios se reúnen, de preferencia en persona, y abren las tarjetas en un solo dispositivo.',
  'Unlock and export': 'Desbloquear y exportar',
  'Safety controls': 'Controles de seguridad',
  'Resume signing': 'Reanudar las firmas',
  'Pause signing': 'Pausar las firmas',
  'Vote to destroy this campaign': 'Votar para destruir esta campaña',
  'Destroying deletes every card and the whole campaign for good. It needs {k} trustees to agree. Vote to destroy?': 'Destruir borra todas las tarjetas y toda la campaña para siempre. Se necesita el acuerdo de {k} custodios. ¿Votar para destruir?',
  'The campaign was destroyed.': 'La campaña fue destruida.',
  'Your vote is recorded ({a} of {k}).': 'Tu voto quedó registrado ({a} de {k}).',
  'Pausing stops new signatures (for example if a link leaked). Destroying deletes everything. Destroy after you have moved to a workspace.': 'Pausar detiene las firmas nuevas (por ejemplo, si se filtró un enlace). Destruir borra todo. Destruye la campaña después de pasar a un espacio del sindicato.',
  'Votes to destroy so far: {a} of {k}.': 'Votos para destruir hasta ahora: {a} de {k}.',
  'Lock this dashboard': 'Bloquear este panel',
  'Confirmed.': 'Confirmado.',
  'Ask {name} to read you the key words on their own screen.': 'Pide a {name} que te lea las palabras clave que aparecen en su propia pantalla.',
  'These match what {name} read to me': 'Coinciden con lo que {name} me leyó',
  'First check each trustee\'s key words with them.': 'Primero comprueba con cada custodio sus palabras clave.',
  'Done. The committee is confirmed and the early cards are locked to it: any {k} of {n} trustees are now needed to open them.': 'Listo. El comité está confirmado y las primeras tarjetas quedaron cerradas para él: ahora se necesitan {k} de los {n} custodios para abrirlas.',
  'Done. The committee is confirmed.': 'Listo. El comité está confirmado.',
  'Done. Any {k} of {n} trustees are now needed to open the cards.': 'Listo. Ahora se necesitan {k} de los {n} custodios para abrir las tarjetas.',
  'Only trustee 1 can open the cards right now.': 'En este momento solo el custodio 1 puede abrir las tarjetas.',
  'Invite the other trustees below. When all {n} have joined, trustee 1 confirms the committee so that {k} of them are needed.': 'Invita abajo a los demás custodios. Cuando se hayan unido los {n}, el custodio 1 confirma el comité para que se necesiten {k} de ellos.',
  'Everyone has joined. Now confirm the committee.': 'Ya se unieron todos. Ahora confirma el comité.',
  'Check each trustee\'s key words with them below, then confirm. That is what lets everyone who signs a card check that they are sealing to the real committee.': 'Comprueba abajo con cada custodio sus palabras clave y luego confirma. Eso es lo que permite que todos los que firman una tarjeta comprueben que la están sellando para el comité verdadero.',
  '{n} early card(s) are still sealed to you alone; confirming also locks them to the committee.': '{n} de las primeras tarjetas siguen selladas solo para ti; al confirmar, también quedan cerradas para el comité.',
  'Everyone has joined.': 'Ya se unieron todos.',
  'Trustee 1 is checking each trustee\'s key words and will confirm the committee. Until then, cards are sealed to trustee 1 alone.': 'El custodio 1 está comprobando las palabras clave de cada custodio y confirmará el comité. Hasta entonces, las tarjetas están selladas solo para el custodio 1.',
  'The committee on the server does not check out.': 'El comité que está en el servidor no pasa la comprobación.',
  'The committee is confirmed.': 'El comité está confirmado.',
  '{n} early card(s) are still sealed to the founder alone.': '{n} de las primeras tarjetas siguen selladas solo para quien fundó la campaña.',
  'The committee is confirmed: any {k} of {n} trustees together can open the cards.': 'El comité está confirmado: cualquier grupo de {k} de los {n} custodios puede abrir las tarjetas en conjunto.',
  'Your key is in the roster the founder signed.': 'Tu llave está en la lista que firmó quien fundó la campaña.',
  '(This device holds no key check from its invitation, so it could not verify the roster.)': '(Este dispositivo no tiene la comprobación de llave de su invitación, así que no pudo verificar la lista.)',
  'Your committee': 'Tu comité',
  'Read these to trustee 1 by phone or in person. They check them before the committee is confirmed, so nobody can slip in a different key.': 'Léeselas al custodio 1 por teléfono o en persona. Las comprobará antes de confirmar el comité, para que nadie pueda colar una llave distinta.',
  '(you)': '(tú)',
  'joined': 'se unió',
  'not joined yet': 'aún no se une',
  'Get invite link': 'Obtener enlace de invitación',
  'Trustee 1 sends this invitation.': 'El custodio 1 envía esta invitación.',
  'First check each trustee\'s key words with them, above.': 'Primero comprueba arriba con cada custodio sus palabras clave.',
  'You are signing this: any {k} of the {n} trustees together can open the cards.': 'Estás firmando esto: cualquier grupo de {k} de los {n} custodios puede abrir las tarjetas en conjunto.',
  'If that is not what you chose, do not confirm.': 'Si eso no es lo que elegiste, no confirmes.',
  'Confirm the committee and lock {n} early card(s)': 'Confirmar el comité y cerrar {n} de las primeras tarjetas',
  'Confirm the committee': 'Confirmar el comité',
  'Lock {n} early card(s) to the committee': 'Cerrar {n} de las primeras tarjetas para el comité',
  'Only trustee 1 holds the keys to these cards, so trustee 1 does this step.': 'Solo el custodio 1 tiene las llaves de estas tarjetas, así que el custodio 1 hace este paso.',
  'Change the plan': 'Cambiar el plan',
  'You can change how many trustees you plan to have, and how many must be together to open the cards, until everyone has joined.': 'Hasta que todos se hayan unido, puedes cambiar cuántos custodios piensas tener y cuántos tienen que estar juntos para abrir las tarjetas.',
  'Trustees': 'Custodios',
  'Needed together': 'Necesarios en conjunto',
  'Save the plan': 'Guardar el plan',
  'The lock': 'El seguro',
  'The cards stay sealed until this many people have signed and been counted. Any trustee can raise the number. Lowering it takes {k} trustees agreeing on the same number.': 'Las tarjetas permanecen selladas hasta que esta cantidad de personas haya firmado y sido contada. Cualquier custodio puede subir el número. Para bajarlo, {k} custodios tienen que ponerse de acuerdo en el mismo número.',
  'Number of people': 'Número de personas',
  'Set the number': 'Fijar el número',
  'The number is now {n}.': 'El número ahora es {n}.',
  'Your vote to lower it to {n} is recorded ({a} of {k}).': 'Tu voto para bajarlo a {n} quedó registrado ({a} de {k}).',
  '{c} trustee(s) have voted to lower it to {v}.': '{c} custodio(s) votaron para bajarlo a {v}.',
  'Where the count comes from': 'De dónde sale el conteo',
  'A card from a direct invitation counts as soon as it is signed. If one person accounts for many of the cards, check with them before relying on the number.': 'Una tarjeta de una invitación directa cuenta en cuanto se firma. Si muchas de las tarjetas vienen de una sola persona, habla con ella antes de confiar en el número.',
  '{c} from invitations made by trustee {i}': '{c} de invitaciones hechas por el custodio {i}',
  '{c} from invitations made by {m} member(s)': '{c} de invitaciones hechas por {m} miembro(s)',
  '(at most {n} from any one member)': '(como máximo {n} de un mismo miembro)',
  '{c} from group links, confirmed in person': '{c} de enlaces de grupo, confirmadas en persona',
  '{c} invited by a member who has since withdrawn': '{c} invitadas por un miembro que después se retiró',
  'Reports from coworkers': 'Reportes de compañeros',
  'Coworkers can choose to share something that happened to them. You can read these; the website cannot.': 'Los compañeros pueden decidir compartir algo que les pasó. Tú puedes leerlos; el sitio web no.',
  'Read {n} report(s)': 'Leer {n} reporte(s)',
  'No reports yet': 'Todavía no hay reportes',
  'From: {x}': 'De: {x}',
  'Shared without a name.': 'Compartido sin nombre.',
  'Mark handled and delete': 'Marcar como atendido y eliminar',
  'Prepare a charge worksheet (draft)': 'Preparar una hoja de trabajo para un cargo (borrador)',
  'This is the ceremony. Trustees load their key files one at a time on this device. When enough have contributed, the cards are opened here, in this browser. Nothing decrypted is ever sent to the server.': 'Esta es la ceremonia. Los custodios cargan sus archivos de llave uno por uno en este dispositivo. Cuando hayan contribuido suficientes, las tarjetas se abren aquí, en este navegador. Nunca se envía al servidor nada descifrado.',
  'First, check the software.': 'Primero, comprueba el software.',
  'Compare this fingerprint with the other trustees\' screens and with the published release before you go on. If they differ, stop.': 'Compara esta huella digital con las pantallas de los demás custodios y con la versión publicada antes de seguir. Si no coinciden, detente.',
  '(could not read)': '(no se pudo leer)',
  'What is this?': '¿Qué es esto?',
  'Do this on a private device you trust, not a work computer. When you are finished, close the tab.': 'Haz esto en un dispositivo privado de tu confianza, no en una computadora del trabajo. Cuando termines, cierra la pestaña.',
  'Begin': 'Comenzar',
  'Founder key': 'Llave de quien fundó la campaña',
  'Trustee {i} of {k}': 'Custodio {i} de {k}',
  'The cards are still locked.': 'Las tarjetas siguen cerradas.',
  '{have} of the {need} people needed have signed and been counted. Nothing can be opened until then, not even by all the trustees together.': 'Han firmado y sido contadas {have} de las {need} personas necesarias. No se puede abrir nada hasta entonces, ni siquiera todos los custodios juntos.',
  'Back to the dashboard': 'Volver al panel',
  '{union}: {n} signed cards.': '{union}: {n} tarjetas firmadas.',
  'Some cards were signed before your committee was complete, so only trustee 1 can open them. Load trustee 1\'s key file.': 'Algunas tarjetas se firmaron antes de que el comité estuviera completo, así que solo el custodio 1 puede abrirlas. Carga el archivo de llave del custodio 1.',
  'Contributed so far: trustees {list}.': 'Han contribuido hasta ahora: custodios {list}.',
  'Enough trustees have contributed.': 'Ya contribuyeron suficientes custodios.',
  'Load your key file': 'Carga tu archivo de llave',
  'Contribute my key': 'Aportar mi llave',
  'You are below a majority. Opening now means the names exist in readable form on this device, before you have the support you planned for. Continue?': 'Están por debajo de una mayoría. Abrir ahora significa que los nombres quedan legibles en este dispositivo antes de tener el apoyo que planearon. ¿Continuar?',
  'The cards are open': 'Las tarjetas están abiertas',
  'The names are now readable on this screen. Do not leave this page open on a shared device.': 'Ahora los nombres se pueden leer en esta pantalla. No dejes esta página abierta en un dispositivo compartido.',
  'Summary': 'Resumen',
  'cards opened': 'tarjetas abiertas',
  'will be in the package ({p}% of about {size})': 'estarán en el paquete ({p}% de unas {size})',
  'disavowed by the signer (excluded unless you include them)': 'desconocidas por quien firmó (excluidas a menos que las incluyas)',
  'without a confirmation email sent': 'sin correo de confirmación enviado',
  'possible duplicate emails or phone numbers to check by hand': 'posibles correos o teléfonos duplicados para revisar a mano',
  'whose card text does not match its fingerprint (marked in the package; check them by hand)': 'cuyo texto no coincide con su huella digital (marcadas en el paquete; revísalas a mano)',
  '{n} card(s) could not be opened. Check that the right key files were used, or that the card was not damaged.': 'No se pudieron abrir {n} tarjeta(s). Comprueba que se usaron los archivos de llave correctos o que la tarjeta no se dañó.',
  'This is not yet a majority. The letter in the package will say so and should not be sent as written.': 'Esto todavía no es una mayoría. La carta del paquete lo dirá y no se debe enviar tal como está.',
  'Include disavowed cards (marked) for review': 'Incluir las tarjetas desconocidas (marcadas) para revisarlas',
  'Download the package': 'Descargar el paquete',
  'A ZIP with the roster, the cards as a PDF, a confirmations log, and draft documents for your attorney to review. It is built here on your device.': 'Un ZIP con la lista, las tarjetas en PDF, un registro de confirmaciones y borradores de documentos para que los revise tu abogado. Se arma aquí, en tu dispositivo.',
  'Download package (ZIP)': 'Descargar el paquete (ZIP)',
  'Package downloaded. Keep it private.': 'Paquete descargado. Mantenlo en privado.',
  'Preview the roster': 'Vista previa de la lista',
  'Name': 'Nombre',
  'Signed': 'Firmada',
  'Confirmation': 'Confirmación',
  'When you are done': 'Cuando termines',
  'Close this tab. To delete the campaign, go back to the trustee dashboard and vote to destroy it.': 'Cierra esta pestaña. Para borrar la campaña, vuelve al panel de custodio y vota para destruirla.',
  // union workspace (workspace.js) (first draft, needs a native reviewer: #10)
  'This link is incomplete. Ask for it to be sent again, and copy the whole link.': 'Este enlace está incompleto. Pide que te lo envíen de nuevo y copia el enlace completo.',
  'This link was already used or is not valid. If you already claimed your account, sign in with your key file.': 'Este enlace ya se usó o no es válido. Si ya activaste tu cuenta, inicia sesión con tu archivo de llave.',
  'Welcome to {union}': 'Bienvenido a {union}',
  'Your union has set up a workspace. Claim your account to vote, get help, and see how the union is run.': 'Tu sindicato creó un espacio en línea. Activa tu cuenta para votar, pedir ayuda y ver cómo se dirige el sindicato.',
  'You sign in with a key file and a passphrase that only you have. There is no password reset, so save both.': 'Inicias sesión con un archivo de llave y una frase de acceso que solo tú tienes. No hay forma de restablecer la contraseña, así que guarda los dos.',
  '2. Save your key file': '2. Guarda tu archivo de llave',
  'Claim my account': 'Activar mi cuenta',
  'Open your union workspace': 'Abre el espacio de tu sindicato',
  'Unlock your account key file to continue.': 'Desbloquea el archivo de llave de tu cuenta para continuar.',
  '{union} account (…{id})': 'Cuenta de {union} (…{id})',
  'New here? Open the account link you were sent to claim your account. Starting a brand new union? Begin with a campaign.': '¿Eres nuevo aquí? Abre el enlace de cuenta que te enviaron para activar tu cuenta. ¿Vas a formar un sindicato desde cero? Empieza con una campaña.',
  'Hello, {name}': 'Hola, {name}',
  'Unit employee': 'Empleado de la unidad',
  'You are a unit employee. You can get help and see the contract no matter what. To vote and see the union\'s money, join the union.': 'Eres empleado de la unidad. Puedes pedir ayuda y ver el contrato pase lo que pase. Para votar y ver el dinero del sindicato, afíliate al sindicato.',
  'Join the union': 'Afiliarme al sindicato',
  'What is happening': 'Qué está pasando',
  'closes {d}': 'cierra el {d}',
  'Vote now': 'Votar ahora',
  'You have voted on everything that is open.': 'Ya votaste en todo lo que está abierto.',
  'No votes are open right now.': 'No hay votaciones abiertas en este momento.',
  'Qualified petition': 'Petición que alcanzó las firmas',
  'Get help': 'Pedir ayuda',
  'Anyone in the unit can raise a workplace problem. It is encrypted so only the people helping you can read it.': 'Cualquier persona de la unidad puede plantear un problema en el trabajo. Se cifra para que solo las personas que te ayudan puedan leerlo.',
  'Tell us what happened': 'Cuéntanos qué pasó',
  'Know your rights': 'Conoce tus derechos',
  'Case': 'Caso',
  'How healthy is the union?': '¿Qué tan fuerte está el sindicato?',
  'Numbers only, never names. Groups smaller than 5 are hidden.': 'Solo números, nunca nombres. Los grupos de menos de 5 se ocultan.',
  'of the unit are members': 'de la unidad son miembros',
  'open cases': 'casos abiertos',
  'overdue steps': 'pasos vencidos',
  'average vote turnout': 'participación promedio en las votaciones',
  'votes held': 'votaciones realizadas',
  'too few to show': 'muy pocos para mostrar',
  'Announcements': 'Anuncios',
  'Nothing posted yet.': 'Todavía no se ha publicado nada.',
  'Post an announcement': 'Publicar un anuncio',
  'Title': 'Título',
  'Message': 'Mensaje',
  'Post': 'Publicar',
  'Where is your union in the process?': '¿En qué etapa del proceso está tu sindicato?',
  'Recognized means your employer recognized you, or the labor board certified you. Cases and bargaining tools turn on. Add a note (for example, a case number).': 'Reconocido significa que tu empleador los reconoció o que la junta laboral los certificó. Se activan las herramientas de casos y de negociación. Agrega una nota (por ejemplo, un número de caso).',
  'Note or case number': 'Nota o número de caso',
  'Save': 'Guardar',
  'Your union': 'Tu sindicato',
  'Our rules (bylaws)': 'Nuestras reglas (estatutos)',
  'Rule settings': 'Valores de las reglas',
  'To change a rule, start a bylaws vote from the Votes tab. If it passes, the rule changes by itself.': 'Para cambiar una regla, inicia una votación de estatutos desde la pestaña Votaciones. Si se aprueba, la regla cambia por sí sola.',
  'History': 'Historial',
  'Who holds what role': 'Quién ocupa cada cargo',
  'since {d}': 'desde el {d}',
  'Give role': 'Asignar cargo',
  'Remove role': 'Quitar cargo',
  'People ({n})': 'Personas ({n})',
  'Every time you view this list, it is recorded and each person can see that you looked.': 'Cada vez que ves esta lista, queda registrado y cada persona puede ver que la consultaste.',
  'Status': 'Estado',
  'Contact': 'Contacto',
  'Shift': 'Turno',
  'Account': 'Cuenta',
  'Member': 'Miembro',
  'not claimed': 'sin activar',
  'Add people': 'Agregar personas',
  'One person per line: name, email, phone, job title, shift. They get a link to claim their account.': 'Una persona por línea: nombre, correo, teléfono, puesto, turno. Cada una recibe un enlace para activar su cuenta.',
  'Add and get claim links': 'Agregar y obtener enlaces de activación',
  'Add at least one person.': 'Agrega al menos a una persona.',
  'New accounts': 'Cuentas nuevas',
  'My information': 'Mi información',
  'Only you and the officers who need it can see this. Your name and email are set by the union; ask an officer to change them.': 'Solo tú y los dirigentes que lo necesitan pueden ver esto. Tu nombre y correo los fija el sindicato; pide a un dirigente que los cambie.',
  'Phone': 'Teléfono',
  'Home address (for mailed election notices)': 'Domicilio (para los avisos de elecciones por correo postal)',
  'Saved.': 'Guardado.',
  'Who has looked at my record': 'Quién ha consultado mi registro',
  'Someone': 'Alguien',
  'viewed your details': 'vio tus datos',
  'opened your case': 'abrió tu caso',
  'Nobody but you.': 'Nadie más que tú.',
  'Legal deadlines and filings': 'Plazos y trámites legales',
  'Suggested dates only. Have your attorney and accountant confirm each one. Project Ludlow never files anything for you.': 'Son solo fechas sugeridas. Pide a tu abogado y a tu contador que confirmen cada una. Project Ludlow nunca presenta nada por ti.',
  'Done': 'Hecho',
  'No fixed date': 'Sin fecha fija',
  'Suggested date: {d}': 'Fecha sugerida: {d}',
  'Mark not done': 'Marcar como pendiente',
  'Mark done': 'Marcar como hecho',
  'Your data belongs to the union': 'Tus datos pertenecen al sindicato',
  'Download everything: members, roles, votes, the whole ledger, rules and the audit log. Private cases stay encrypted, and only the people who hold their keys can read them. The download itself is recorded in the audit log.': 'Descarga todo: miembros, cargos, votaciones, todo el libro de cuentas, las reglas y el registro de auditoría. Los casos privados siguen cifrados y solo pueden leerlos las personas que tienen sus llaves. La descarga misma queda anotada en el registro de auditoría.',
  'Export everything (JSON)': 'Exportar todo (JSON)',
  'Exported. This file contains personal information: keep it private.': 'Exportado. Este archivo contiene información personal: mantenlo en privado.',
  'Audit log': 'Registro de auditoría',
  'The audit log has been tampered with near entry {n}. Do not trust it.': 'Alguien manipuló el registro de auditoría cerca de la entrada {n}. No confíes en él.',
  'The history changed.': 'El historial cambió.',
  'On an earlier visit this device saw audit entries that are now different or missing. Someone may have rewritten the log. Tell your members right away.': 'En una visita anterior, este dispositivo vio entradas de auditoría que ahora son distintas o ya no están. Puede que alguien haya reescrito el registro. Avísales a tus miembros de inmediato.',
  'Checked in your browser: all {n} entries form an unbroken chain from the first. This is the first check on this device, so it cannot yet tell whether entries were rewritten before today. Later visits will.': 'Comprobado en tu navegador: las {n} entradas forman una cadena sin cortes desde la primera. Es la primera comprobación en este dispositivo, así que todavía no puede saber si se reescribieron entradas antes de hoy. Las próximas visitas sí podrán.',
  'Checked in your browser: all {n} entries form an unbroken chain from the first, and entries this device saw before have not changed.': 'Comprobado en tu navegador: las {n} entradas forman una cadena sin cortes desde la primera, y las entradas que este dispositivo vio antes no han cambiado.',
  'Who': 'Quién',
  'What': 'Qué',
  'When': 'Cuándo',
  'Show older entries': 'Mostrar entradas anteriores',
  'Steward': 'Delegado',
  // votes and petitions (ws-votes.js) (first draft, needs a native reviewer: #10)
  'If this passes, dues become {amount}.': 'Si esto se aprueba, la cuota será de {amount}.',
  'If this passes, these rules change automatically: {list}.': 'Si esto se aprueba, estas reglas cambian automáticamente: {list}.',
  'If a majority votes to remove, the role ends automatically.': 'Si una mayoría vota por destituir, el cargo termina automáticamente.',
  'Please give it a title.': 'Por favor ponle un título.',
  'Enter the dues amount.': 'Escribe el monto de la cuota.',
  'Enter the new value.': 'Escribe el nuevo valor.',
  'Petition started. You are the first signature.': 'Petición iniciada. Tu firma es la primera.',
  'You need at least two election committee members with claimed accounts before you can hold a vote.': 'Necesitas al menos dos miembros del comité electoral con su cuenta activada antes de poder hacer una votación.',
  'The vote is open.': 'La votación está abierta.',
  'Start a petition': 'Iniciar una petición',
  'Start a vote': 'Iniciar una votación',
  'If enough members sign, the election committee must open this vote exactly as you write it.': 'Si firman suficientes miembros, el comité electoral debe abrir esta votación exactamente como tú la escribas.',
  'What are members deciding?': '¿Qué están decidiendo los miembros?',
  'Explain it (optional)': 'Explícalo (opcional)',
  'Kind of decision': 'Tipo de decisión',
  'Name of the dues plan': 'Nombre del plan de cuotas',
  'Amount per month': 'Monto por mes',
  'Rule to change': 'Regla que se cambia',
  'New value': 'Nuevo valor',
  'Who and which role?': '¿Quién y qué cargo?',
  'Choices (one per line, the first is "Yes")': 'Opciones (una por línea; la primera es "Sí")',
  'It passes with': 'Se aprueba con',
  'Voting stays open for (days)': 'La votación queda abierta durante (días)',
  'Start the petition': 'Iniciar la petición',
  'Open the vote': 'Abrir la votación',
  'Counting': 'En conteo',
  'Passed': 'Aprobada',
  'Did not pass': 'No aprobada',
  'Votes': 'Votaciones',
  'Every vote is a secret ballot. The committee counts in a browser, and afterward any member can recount.': 'Toda votación es con papeleta secreta. El comité cuenta en un navegador y después cualquier miembro puede volver a contar.',
  'closed': 'cerrada',
  '{a} of {b} voted': 'votaron {a} de {b}',
  'No votes yet.': 'Todavía no hay votaciones.',
  'Petitions': 'Peticiones',
  'Collecting signatures': 'Reuniendo firmas',
  'Overdue: the committee has not opened it': 'Vencida: el comité no la ha abierto',
  'Qualified: the committee must open it': 'Alcanzó las firmas: el comité debe abrirla',
  'Opened': 'Abierta',
  'The bylaws give the election committee 14 days to open a qualified petition, and that time has passed. Ask them why, and raise it at the next meeting.': 'Los estatutos le dan al comité electoral 14 días para abrir una petición que alcanzó las firmas, y ese plazo ya pasó. Pregúntales por qué y plantéalo en la próxima reunión.',
  '{a} of {b} signatures needed.': '{a} de {b} firmas necesarias.',
  'The committee should open it by {d}.': 'El comité debería abrirla a más tardar el {d}.',
  'Sign this petition': 'Firmar esta petición',
  'You signed.': 'Firmaste.',
  'Open for (days)': 'Abierta durante (días)',
  'Open this vote': 'Abrir esta votación',
  'No petitions.': 'No hay peticiones.',
  'All votes': 'Todas las votaciones',
  'Voting is closed': 'La votación está cerrada',
  'The election committee counts the ballots together. Results appear here when they are done.': 'El comité electoral cuenta las papeletas en conjunto. Los resultados aparecerán aquí cuando terminen.',
  'Committee: {names}. {k} of them must be together to count.': 'Comité: {names}. Tienen que estar juntos {k} de ellos para contar.',
  'Count the ballots': 'Contar las papeletas',
  'You have voted.': 'Ya votaste.',
  'Your receipt code was shown when you voted.': 'Tu código de comprobante se mostró cuando votaste.',
  'Cast your secret ballot': 'Emite tu voto secreto',
  'Your ballot is stored without your name or the time you voted, so officers and other members cannot see how you voted. You cannot change your vote afterward.': 'Tu papeleta se guarda sin tu nombre ni la hora en que votaste, así que ni los dirigentes ni los demás miembros pueden ver cómo votaste. No puedes cambiar tu voto después.',
  'Cast my ballot': 'Emitir mi voto',
  'Choose an option first.': 'Primero elige una opción.',
  'Only members can vote. Join the union from the Home tab to take part in the next one.': 'Solo los miembros pueden votar. Afíliate al sindicato desde la pestaña Inicio para participar en la próxima.',
  'Close voting now': 'Cerrar la votación ahora',
  'Close voting now? No more ballots can be cast.': '¿Cerrar la votación ahora? Ya no se podrán emitir más votos.',
  'Your receipt code': 'Tu código de comprobante',
  'After the count, use this code to check that your ballot is in the list. It proves you voted, not how.': 'Después del conteo, usa este código para comprobar que tu papeleta está en la lista. Demuestra que votaste, no cómo votaste.',
  'Results': 'Resultados',
  '{a} of {b} eligible members voted. {c} ballots counted.': 'Votaron {a} de {b} miembros con derecho a voto. Se contaron {c} papeletas.',
  '{n} ballot(s) could not be read and were not counted.': 'No se pudieron leer {n} papeleta(s) y no se contaron.',
  'This decision has been carried out automatically.': 'Esta decisión se aplicó automáticamente.',
  'Check the count yourself': 'Comprueba el conteo tú mismo',
  'Your receipt is in the list, so your vote was recorded.': 'Tu comprobante está en la lista, así que tu voto quedó registrado.',
  'Your receipt was NOT found in the list. Tell the committee.': 'Tu comprobante NO aparece en la lista. Avísale al comité.',
  'Check a receipt code': 'Comprobar un código de comprobante',
  'Check': 'Comprobar',
  'That receipt is in the list.': 'Ese comprobante está en la lista.',
  'That receipt is not in the list.': 'Ese comprobante no está en la lista.',
  'Recount every ballot in my browser': 'Volver a contar todas las papeletas en mi navegador',
  'Your browser recounted {n} ballots and got exactly the published result. That shows the published numbers match the ballots stored on the server; it cannot show that a ballot was never replaced before the key was published.': 'Tu navegador volvió a contar {n} papeletas y obtuvo exactamente el resultado publicado. Eso demuestra que los números publicados coinciden con las papeletas guardadas en el servidor; no puede demostrar que ninguna papeleta se haya reemplazado antes de publicar la llave.',
  'Your recount does NOT match the published result. Raise this with the committee.': 'Tu reconteo NO coincide con el resultado publicado. Plantéaselo al comité.',
  'The committee counted privately and did not publish the key, so a recount is not possible for this vote.': 'El comité contó en privado y no publicó la llave, así que no es posible volver a contar esta votación.',
  'Those key files could not open the ballots.': 'Esos archivos de llave no pudieron abrir las papeletas.',
  '{a} of {k} committee members have contributed.': 'Han contribuido {a} de {k} miembros del comité.',
  'Next committee member': 'Siguiente miembro del comité',
  'Contribute': 'Aportar',
  'Counted': 'Conteo terminado',
  '{n} ballot(s) could not be read.': 'No se pudieron leer {n} papeleta(s).',
  'This passes.': 'Esto se aprueba.',
  'This does not pass.': 'Esto no se aprueba.',
  'The ballot key will be published.': 'Se publicará la llave de las papeletas.',
  'This decision changes the dues, the rules or who holds a role, so anyone must be able to recount it.': 'Esta decisión cambia las cuotas, las reglas o quién ocupa un cargo, así que cualquiera debe poder volver a contarla.',
  'Publish the ballot key so every member can recount (recommended)': 'Publicar la llave de las papeletas para que cada miembro pueda volver a contar (recomendado)',
  'Ballots are not linked to voters, so publishing the key shows how many chose what, not who. It lets any member check the count.': 'Las papeletas no están vinculadas a quienes votaron, así que publicar la llave muestra cuántos eligieron cada opción, no quiénes. Permite que cualquier miembro compruebe el conteo.',
  'But once it is published, anyone who kept a copy of their own encrypted ballot can prove how they voted. If members could be pressured to show their vote (a strike or a contract vote, say), think about that before publishing.': 'Pero una vez publicada, cualquiera que haya guardado una copia de su propia papeleta cifrada puede demostrar cómo votó. Si se pudiera presionar a los miembros para que muestren su voto (en una votación de huelga o de contrato, por ejemplo), piénsalo antes de publicarla.',
  'Without the key nobody can recount. Each of the {k} committee members who counted signs these numbers, and the server accepts them only with all {k} signatures.': 'Sin la llave nadie puede volver a contar. Cada uno de los {k} miembros del comité que contaron firma estos números, y el servidor los acepta solo con las {k} firmas.',
  'Publish the results': 'Publicar los resultados',
  'A question for the members': 'Una pregunta para los miembros',
  'Change a rule (bylaws)': 'Cambiar una regla (estatutos)',
  'Ratify a contract or agreement': 'Ratificar un contrato o acuerdo',
  'Set the dues': 'Fijar la cuota',
  'Strike authorization': 'Autorización de huelga',
  'Remove someone from a role (recall)': 'Quitar a alguien de un cargo (destitución)',
  'A majority of votes cast': 'La mayoría de los votos emitidos',
  'Two thirds of votes cast': 'Dos tercios de los votos emitidos',
  'The option with the most votes': 'La opción con más votos',
  // getting help and cases (ws-help.js) (first draft, needs a native reviewer: #10)
  'If something at work is not right, tell us. Anyone in the unit can do this, member or not, and it never depends on dues.': 'Si algo en el trabajo no está bien, avísanos. Cualquier persona de la unidad puede hacerlo, sea miembro o no, y nunca depende de las cuotas.',
  'In a meeting with a manager? Know your Weingarten rights': '¿Estás en una reunión con un gerente? Conoce tus derechos Weingarten',
  'This is locked so that only you, the chief stewards and any steward your case is shared with can read it. Other officers cannot. The keys it is locked to come from this website, so for now you are trusting the website to hand out the right ones.': 'Esto se cifra para que solo tú, los delegados principales y cualquier delegado con quien se comparta tu caso puedan leerlo. Los demás dirigentes no pueden. Las llaves con las que se cifra vienen de este sitio web, así que por ahora confías en que el sitio entregue las correctas.',
  'When?': '¿Cuándo?',
  'Contract article, number only (if you know it). This one is not encrypted.': 'Artículo del contrato, solo el número (si lo sabes). Este dato no se cifra.',
  'What would fix it?': '¿Qué lo resolvería?',
  'Send it, encrypted': 'Enviarlo cifrado',
  'Put only the article number there, such as "Art. 12". Everything else belongs in the description, which is encrypted.': 'Pon ahí solo el número del artículo, por ejemplo "Art. 12". Todo lo demás va en la descripción, que sí se cifra.',
  'Sent. A steward will be assigned.': 'Enviado. Se asignará un delegado.',
  'Formal cases turn on once your union is recognized. Until then, talk to a steward or officer in person.': 'Los casos formales se activan cuando tu sindicato esté reconocido. Mientras tanto, habla en persona con un delegado o un dirigente.',
  'All cases': 'Todos los casos',
  'Your cases': 'Tus casos',
  'filed {d}': 'presentado el {d}',
  'Closed': 'Cerrado',
  'Open': 'Abierto',
  'Steward: {name}': 'Delegado: {name}',
  'Waiting for a steward.': 'Esperando a un delegado.',
  'There is an update on your case.': 'Hay una novedad en tu caso.',
  'Grievance steps and deadlines (officers)': 'Pasos y plazos de las quejas (dirigentes)',
  'One step per line: name | days | business or calendar. These deadlines come from your contract. Deadlines are counted for you and stewards get reminders.': 'Un paso por línea: nombre | días | business (hábiles) o calendar (naturales). Estos plazos vienen de tu contrato. Los plazos se cuentan automáticamente y los delegados reciben recordatorios.',
  'Holidays (one date per line, YYYY-MM-DD)': 'Días feriados (una fecha por línea, AAAA-MM-DD)',
  'Save steps': 'Guardar los pasos',
  'Filed {d}': 'Presentado el {d}',
  'No steward yet': 'Todavía sin delegado',
  'What happened': 'Qué pasó',
  'When: {x}': 'Cuándo: {x}',
  'Who: {x}': 'Quién: {x}',
  'What would fix it: {x}': 'Qué lo resolvería: {x}',
  'You do not hold the key to read this case. Ask the worker, or a steward who is on the case, to share it with you.': 'No tienes la llave para leer este caso. Pide al trabajador, o a un delegado que lleve el caso, que lo comparta contigo.',
  'Not everyone who should can read this case': 'No todas las personas que deberían pueden leer este caso',
  'These chief stewards were appointed after the case was filed, so they cannot read or work it until someone who holds the key shares it with them. Sharing seals the key to them alone.': 'Estos delegados principales fueron nombrados después de que se presentó el caso, así que no pueden leerlo ni trabajarlo hasta que alguien que tenga la llave lo comparta con ellos. Compartir sella la llave solo para ellos.',
  'Share this case with {name}': 'Compartir este caso con {name}',
  'Steps and deadlines': 'Pasos y plazos',
  'business days': 'días hábiles',
  'calendar days': 'días naturales',
  'done {d}': 'hecho el {d}',
  'due {d}': 'vence el {d}',
  'Decision': 'Decisión',
  'The worker has been told.': 'Ya se le avisó al trabajador.',
  'The worker has not been told yet.': 'Todavía no se le ha avisado al trabajador.',
  'Notes': 'Notas',
  '(cannot read)': '(no se puede leer)',
  'Assign a steward': 'Asignar un delegado',
  'The case key is also sealed to the steward you assign, so they can read it too.': 'La llave del caso también se sella para el delegado que asignes, así que también podrá leerlo.',
  'Assign': 'Asignar',
  'Work on this case': 'Trabajar en este caso',
  'Add a note (encrypted)': 'Agregar una nota (cifrada)',
  'Save note': 'Guardar la nota',
  'Complete this step': 'Completar este paso',
  'Decision and closing': 'Decisión y cierre',
  'Every case must end with a decision, a reason, and telling the worker. That protects the worker and the union.': 'Todo caso debe terminar con una decisión, una razón y un aviso al trabajador. Eso protege al trabajador y al sindicato.',
  'Reason (the worker will read this)': 'Razón (el trabajador la leerá)',
  'Record decision': 'Registrar la decisión',
  'Please give a reason.': 'Por favor da una razón.',
  'Tell the worker': 'Avisar al trabajador',
  'Close the case': 'Cerrar el caso',
  'Before closing: {list}.': 'Antes de cerrar: {list}.',
  'record a decision': 'registra una decisión',
  'give a reason': 'da una razón',
  'tell the worker': 'avisa al trabajador',
  'We will pursue this': 'Vamos a seguir adelante con esto',
  'It was resolved informally': 'Se resolvió de manera informal',
  'We will not pursue this': 'No vamos a seguir adelante con esto',
  'Move to the next step': 'Pasar al siguiente paso',
  'Mark this step resolved': 'Marcar este paso como resuelto',
  'Denied: move to the next step': 'Denegado: pasar al siguiente paso',
  // union money (ws-money.js) (first draft, needs a native reviewer: #10)
  'Money': 'Dinero',
  'The books do not add up.': 'Las cuentas no cuadran.',
  'Your browser found that the ledger was changed near entry {n}. Do not trust these numbers. Tell your officers and members right away.': 'Tu navegador detectó que el libro de cuentas se modificó cerca de la entrada {n}. No confíes en estos números. Avísales a tus dirigentes y miembros de inmediato.',
  'On an earlier visit this device saw entries that are now different or missing. Someone may have rewritten the books. Tell your members right away.': 'En una visita anterior, este dispositivo vio entradas que ahora son distintas o ya no están. Puede que alguien haya reescrito las cuentas. Avísales a tus miembros de inmediato.',
  'Who was paid was changed.': 'Se cambió a quién se le pagó.',
  'The payee or note shown for entry {n} is not what was recorded when the entry was made. Do not trust it. Tell your officers and members right away.': 'El beneficiario o la nota que se muestra en la entrada {n} no es lo que se registró cuando se hizo la entrada. No confíes en ella. Avísales a tus dirigentes y miembros de inmediato.',
  'Checked in your browser: all {n} ledger entries form an unbroken chain, and nothing this device saw before has changed.': 'Comprobado en tu navegador: las {n} entradas del libro de cuentas forman una cadena sin cortes, y nada de lo que este dispositivo vio antes ha cambiado.',
  'The payee and note of {c} entries match what was recorded.': 'El beneficiario y la nota de {c} entradas coinciden con lo registrado.',
  'Fingerprint:': 'Huella digital:',
  '(compare with a coworker\'s. If they differ, something is wrong.)': '(compárala con la de un compañero. Si no coinciden, algo está mal.)',
  'in the union\'s account': 'en la cuenta del sindicato',
  'Spending of {x} or more needs two different officers to approve. Nobody approves their own request.': 'Los gastos de {x} o más necesitan la aprobación de dos dirigentes distintos. Nadie aprueba su propia solicitud.',
  'Money in': 'Ingresos',
  'Nothing yet.': 'Nada todavía.',
  'Money out': 'Gastos',
  'Dues': 'Cuotas',
  'Current dues: {name}, {amount} per month.': 'Cuota actual: {name}, {amount} al mes.',
  'See the vote that set it': 'Ver la votación que la fijó',
  'Dues have not been set. Dues can only be set by a vote of the members.': 'Todavía no se ha fijado una cuota. La cuota solo se puede fijar con una votación de los miembros.',
  'Propose dues from the Votes tab': 'Propón una cuota desde la pestaña Votaciones',
  'Waiting for approval or payment': 'Esperando aprobación o pago',
  'Approved: ready to pay': 'Aprobado: listo para pagar',
  '{a} of {n} approvals': '{a} de {n} aprobaciones',
  'Requested by {name}': 'Solicitado por {name}',
  'Approve': 'Aprobar',
  'Reject': 'Rechazar',
  'Mark as paid': 'Marcar como pagado',
  'Record money received': 'Registrar dinero recibido',
  'What kind?': '¿De qué tipo?',
  'Amount': 'Monto',
  'From (visible to members)': 'De (visible para los miembros)',
  'Note (visible to members)': 'Nota (visible para los miembros)',
  'Record': 'Registrar',
  'Ask to spend money': 'Solicitar un gasto',
  'Members can see what you write here, except the name of anyone receiving hardship aid.': 'Los miembros pueden ver lo que escribas aquí, excepto el nombre de quien reciba ayuda por dificultades económicas.',
  'What for?': '¿Para qué?',
  'Paid to': 'Pagado a',
  'Note': 'Nota',
  'Send for approval': 'Enviar para aprobación',
  'Sent. It needs {n} approval(s) from other officers.': 'Enviado. Necesita {n} aprobación(es) de otros dirigentes.',
  'Every entry': 'Todas las entradas',
  'Entries can never be edited or deleted. A mistake is fixed with a new reversing entry.': 'Las entradas nunca se pueden editar ni borrar. Un error se corrige con una nueva entrada de reversión.',
  'Who / note': 'Quién / nota',
  'reverses #{n}': 'revierte la n.º {n}',
  'Reverse': 'Revertir',
  'Why is this being reversed?': '¿Por qué se revierte esto?',
  'Reversed': 'Revertida',
};
