// Spanish (Español). Keys are the English strings used in the app; anything missing shows in English.
// Covers the worker-facing flow: home, signing a card, the member page, the private record, safety.
// TODO(lawyer): have a bilingual attorney or a certified translator review every legal-facing string.
export default {
  // frame
  'Quick exit': 'Salida rápida',
  'Leave this page right now (or press Esc three times)': 'Salir de esta página ahora mismo (o presiona Esc tres veces)',
  'Project Ludlow is a tool. It is not a union and not a law firm.': 'Project Ludlow es una herramienta. No es un sindicato ni un bufete de abogados.',
  'How your data is protected': 'Cómo se protegen tus datos', 'Your rights': 'Tus derechos', 'Safety tips': 'Consejos de seguridad',
  'Verify this software': 'Verificar este software', 'Terms': 'Términos', 'Tab title': 'Título de la pestaña', 'Language': 'Idioma',
  'Copied': 'Copiado', 'Back': 'Atrás', 'Next': 'Siguiente', 'Cancel': 'Cancelar', 'Copy': 'Copiar', 'Delete': 'Eliminar', 'Confirm': 'Confirmar',
  'Share': 'Compartir', 'Copy link': 'Copiar enlace', 'Copy a message to send': 'Copiar un mensaje para enviar', 'Read aloud': 'Leer en voz alta',
  'Page not found': 'Página no encontrada', 'Go to the home page': 'Ir a la página de inicio', 'That did not work.': 'Eso no funcionó.',
  // home
  'Start a union at your workplace, safely.': 'Forma un sindicato en tu lugar de trabajo, de forma segura.',
  'Collect signed authorization cards that only your own committee can ever read. Then run your union openly and fairly, with tools that let every member check the work.': 'Reúne tarjetas de autorización firmadas que solo tu propio comité podrá leer. Luego dirige tu sindicato de forma abierta y justa, con herramientas que permiten a cada miembro comprobar el trabajo.',
  'Start a campaign': 'Empezar una campaña', 'Open my union workspace': 'Abrir el espacio de mi sindicato',
  'Got an invitation link from a coworker? Just open it. You do not need an account.': '¿Recibiste un enlace de invitación de un compañero? Solo ábrelo. No necesitas una cuenta.',
  'How it works': 'Cómo funciona',
  'A few trusted coworkers become trustees.': 'Unos pocos compañeros de confianza se convierten en custodios de las llaves.',
  'You can start alone and add them as you go. Once your committee is complete, any group of them, for example 3 of 5, can open the cards, and only after enough people have signed. No one alone can.': 'Puedes empezar solo y agregarlos poco a poco. Cuando tu comité esté completo, cualquier grupo de ellos, por ejemplo 3 de 5, podrá abrir las tarjetas, y solo después de que firmen suficientes personas. Nadie puede hacerlo solo.',
  'Your card stays sealed. Until at least {n} people have signed and been counted, nobody can open it: not the trustees, and not this website.': 'Tu tarjeta permanece sellada. Hasta que al menos {n} personas hayan firmado y sido contadas, nadie puede abrirla: ni los custodios, ni este sitio web.',
  'Coworkers sign on their own phones.': 'Los compañeros firman en sus propios teléfonos.',
  'Each card is locked on the phone before it is sent. This website only ever sees scrambled data.': 'Cada tarjeta se cifra en el teléfono antes de enviarse. Este sitio web solo ve datos codificados.',
  'You decide when to go public.': 'Ustedes deciden cuándo hacerlo público.',
  'When you have enough support, the trustees open the cards together and get a package to review: a roster, the cards, and draft letters and forms.': 'Cuando tengan suficiente apoyo, los custodios abren las tarjetas juntos y reciben un paquete para revisar: una lista, las tarjetas y borradores de cartas y formularios.',
  'Then run the union in the open.': 'Luego dirijan el sindicato con transparencia.',
  'Votes, money and workplace cases, built so that every member can check that they were done fairly.': 'Votaciones, dinero y casos laborales, diseñados para que cada miembro pueda comprobar que se hicieron con justicia.',
  'Built so you do not have to trust us': 'Diseñado para que no tengas que confiar en nosotros',
  'Cards are encrypted in the browser. Not even this website can read them.': 'Las tarjetas se cifran en el navegador. Ni siquiera este sitio web puede leerlas.',
  'Votes are secret, and after a vote every member can recount the ballots themselves.': 'Los votos son secretos y, después de una votación, cada miembro puede volver a contar las papeletas.',
  "The union's books are a chain that cannot be quietly edited. Your browser checks it.": 'Las cuentas del sindicato forman una cadena que no se puede editar en silencio. Tu navegador la comprueba.',
  'Spending needs two officers. Members can force a vote or a recall by petition.': 'Los gastos necesitan a dos dirigentes. Los miembros pueden exigir una votación o una destitución con una petición.',
  'You can run your own copy of the server and export everything at any time.': 'Puedes ejecutar tu propia copia del servidor y exportar todo en cualquier momento.',
  'This is a tool.': 'Esto es una herramienta.',
  'It is not a union and not a law firm. It never files anything or contacts your employer for you. Everything it produces is a draft for people to review.': 'No es un sindicato ni un bufete de abogados. Nunca presenta nada ni contacta a tu empleador por ti. Todo lo que produce es un borrador para que lo revisen personas.',
  // signing
  'This link is incomplete. Ask for it to be sent again, and make sure the whole link is copied.': 'Este enlace está incompleto. Pide que te lo envíen de nuevo y asegúrate de copiar el enlace completo.',
  'This invitation is no longer valid. It may have expired, been used, or been withdrawn. Ask the person who sent it for a new one.': 'Esta invitación ya no es válida. Puede haber caducado, haberse usado o haberse retirado. Pídele a quien te la envió una nueva.',
  'Coworkers at {employer} are forming a union, and you have been invited to sign an authorization card.': 'Compañeros de {employer} están formando un sindicato y te han invitado a firmar una tarjeta de autorización.',
  'Your information is encrypted on your phone before it is sent. This website cannot read it.': 'Tu información se cifra en tu teléfono antes de enviarse. Este sitio web no puede leerla.',
  'Before you sign': 'Antes de firmar',
  'Use your own phone, on your mobile data, and not at work.': 'Usa tu propio teléfono, con tus datos móviles, y no en el trabajo.',
  'Signing is your choice. Nobody can make you.': 'Firmar es decisión tuya. Nadie puede obligarte.',
  'You will get a confirmation email. If you did not sign, you can tell us.': 'Recibirás un correo de confirmación. Si no firmaste, puedes avisarnos.',
  'The law protects your right to organize.': 'La ley protege tu derecho a organizarte.',
  'Read about your rights': 'Lee sobre tus derechos', 'Read the card': 'Leer la tarjeta', 'Your authorization card': 'Tu tarjeta de autorización', 'Card language': 'Idioma de la tarjeta',
  'Signature (type your name below)': 'Firma (escribe tu nombre abajo)', 'Date: recorded by the server when you sign.': 'Fecha: la registra el servidor cuando firmas.',
  "Encrypted on your device. This site can't read it.": 'Cifrado en tu dispositivo. Este sitio no puede leerlo.',
  'Full legal name': 'Nombre legal completo', 'Personal email': 'Correo electrónico personal',
  'Not your work email. We send a confirmation here, as the law requires.': 'No tu correo del trabajo. Aquí enviamos una confirmación, como exige la ley.',
  'Mobile phone': 'Teléfono móvil', 'Optional details': 'Detalles opcionales', 'Job title': 'Puesto', 'Shift or department': 'Turno o departamento', 'Preferred language': 'Idioma preferido',
  'Please do not enter your date of birth, Social Security number or any ID number.': 'Por favor no escribas tu fecha de nacimiento, número de Seguro Social ni ningún número de identificación.',
  'Type your full name to sign': 'Escribe tu nombre completo para firmar', 'I have read the card above and I agree to it.': 'He leído la tarjeta de arriba y estoy de acuerdo.', 'Sign the card': 'Firmar la tarjeta',
  'Please enter your full legal name.': 'Por favor escribe tu nombre legal completo.', 'Please enter a valid personal email address.': 'Por favor escribe un correo electrónico personal válido.',
  'Please enter a phone number with 10 digits.': 'Por favor escribe un número de teléfono de 10 dígitos.',
  'Please do not enter dates of birth, Social Security numbers or ID numbers. They are not needed and must not be included.': 'Por favor no escribas fechas de nacimiento, números de Seguro Social ni de identificación. No son necesarios y no deben incluirse.',
  'Type your full name exactly as above to sign.': 'Escribe tu nombre completo exactamente como arriba para firmar.', 'Please check the box to agree to the card.': 'Por favor marca la casilla para aceptar la tarjeta.',
  'Almost done': 'Casi listo', 'Your card is signed and counted': 'Tu tarjeta está firmada y contada',
  'Tell this code, in person, to the coworker who invited you:': 'Dile este código, en persona, al compañero que te invitó:',
  'Your card counts once they enter it. Do not send it in a message.': 'Tu tarjeta cuenta cuando él o ella lo ingrese. No lo envíes por mensaje.',
  'Thank you. Your card is counted.': 'Gracias. Tu tarjeta está contada.',
  'We sent a confirmation email to {email}. If you did not sign, the email has a link to tell us.': 'Enviamos un correo de confirmación a {email}. Si no firmaste, el correo tiene un enlace para avisarnos.',
  'Your card is saved, but we could not send the confirmation email.': 'Tu tarjeta está guardada, pero no pudimos enviar el correo de confirmación.', 'Try again': 'Intentar de nuevo',
  'Save your member link': 'Guarda tu enlace de miembro',
  'This link is how you come back to see progress, invite others, and keep your private record. Anyone who has it can act as you, so keep it private, for example in a password manager or a Signal "Note to Self". Nobody, including us, can recover it for you.': 'Con este enlace vuelves para ver el progreso, invitar a otros y llevar tu registro privado. Cualquiera que lo tenga puede actuar como tú, así que guárdalo en privado, por ejemplo en un gestor de contraseñas o en las "Notas para mí" de Signal. Nadie, ni nosotros, puede recuperarlo por ti.',
  'Copy my link': 'Copiar mi enlace', 'Share it to myself': 'Enviármelo a mí', 'Open my page': 'Abrir mi página', 'What happens next': 'Qué sigue',
  'Your coworkers may invite you to help. You decide.': 'Tus compañeros pueden invitarte a ayudar. Tú decides.',
  'Nothing is sent to your employer. The trustees decide together when to go public.': 'No se envía nada a tu empleador. Los custodios deciden juntos cuándo hacerlo público.',
  'If your employer asks about the union, you never have to answer, and you can write it down privately on your member page.': 'Si tu empleador te pregunta por el sindicato, nunca tienes que responder, y puedes anotarlo en privado en tu página de miembro.',
  // member page
  'No card on this device': 'No hay ninguna tarjeta en este dispositivo',
  'Where we are': 'Dónde estamos', 'of about {size} coworkers have signed ({p})': 'de unos {size} compañeros han firmado ({p})', 'Cards signed': 'Tarjetas firmadas',
  'You are signed on at {employer}. Thank you.': 'Ya firmaste en {employer}. Gracias.', 'Bring in a coworker': 'Trae a un compañero',
  'Invite people you know and trust, one at a time. Do it in person or through an app you trust.': 'Invita a personas que conozcas y en quienes confíes, una por una. Hazlo en persona o con una aplicación de confianza.',
  'Invite one person': 'Invitar a una persona', 'Create a group link': 'Crear un enlace de grupo',
  'Hi, some of us at {employer} are forming a union. Please sign a card with this link, on your own phone and not at work: ': 'Hola, algunos de nosotros en {employer} estamos formando un sindicato. Por favor firma una tarjeta con este enlace, en tu propio teléfono y no en el trabajo: ',
  'Anyone who gets this link can sign, but their card will not count until you confirm them in person.': 'Cualquiera que reciba este enlace puede firmar, pero su tarjeta no contará hasta que lo confirmes en persona.',
  'People waiting for you to confirm': 'Personas esperando tu confirmación',
  'Ask each person for the two-word code they were shown. Only enter it if you met them in person.': 'Pídele a cada persona el código de dos palabras que vio. Solo ingrésalo si la conociste en persona.',
  'Confirmed. Their card now counts.': 'Confirmado. Su tarjeta ya cuenta.', 'That code is not right. {n} tries left.': 'Ese código no es correcto. Quedan {n} intentos.',
  'One more is waiting to be confirmed in person.': 'Falta una persona por confirmar en persona.', '{n} more are waiting to be confirmed in person.': 'Faltan {n} personas por confirmar en persona.',
  'Show QR code': 'Mostrar código QR', 'Hide QR code': 'Ocultar código QR', 'Show this only to the person you are inviting.': 'Muéstralo solo a la persona que estás invitando.',
  'Withdraw my card': 'Retirar mi tarjeta', 'Your card was deleted.': 'Tu tarjeta fue eliminada.',
  'Withdraw your card? It is permanently deleted from the server and no longer counts. This cannot be undone.': '¿Retirar tu tarjeta? Se elimina para siempre del servidor y deja de contar. No se puede deshacer.',
  'Your card is waiting to be confirmed by the coworker who invited you.': 'Tu tarjeta está esperando ser confirmada por el compañero que te invitó.', 'Tell them this code, in person:': 'Dile este código, en persona:',
  'Once they confirm you, your card counts and you will see progress here. Nothing else is needed from you.': 'Cuando te confirme, tu tarjeta contará y verás el progreso aquí. No se necesita nada más de ti.',
  'Your member link': 'Tu enlace de miembro', 'Keep it private. It is how you get back here.': 'Mantenlo en privado. Es la forma de volver aquí.',
  'The trustees have paused this campaign. No new cards can be signed for now.': 'Los custodios pausaron esta campaña. Por ahora no se pueden firmar tarjetas nuevas.',
  // private record
  'My private record': 'Mi registro privado',
  'Write down anything that looks like punishment for organizing. Only you can read it. Not the trustees, not this website, unless you choose to share an entry.': 'Anota todo lo que parezca un castigo por organizarse. Solo tú puedes leerlo. Ni los custodios ni este sitio web, a menos que decidas compartir una entrada.',
  'Add something that happened': 'Agregar algo que pasó', 'What happened?': '¿Qué pasó?', 'Date': 'Fecha', 'What was said or done?': '¿Qué se dijo o se hizo?',
  'Write what you saw and heard, in your own words. Facts, not opinions.': 'Escribe lo que viste y oíste, con tus propias palabras. Hechos, no opiniones.',
  'Who was involved?': '¿Quién estuvo involucrado?', 'Who else saw it?': '¿Quién más lo vio?', 'Save privately': 'Guardar en privado', 'Please describe what happened.': 'Por favor describe lo que pasó.',
  'Asked whether I or others support the union': 'Me preguntaron si yo u otros apoyamos al sindicato', 'Threatened me or others': 'Me amenazaron a mí o a otros',
  'Promised a benefit to drop the union': 'Prometieron un beneficio para que abandonara el sindicato', 'Watched or followed union activity': 'Vigilaron o siguieron la actividad sindical',
  'Disciplined, fired or cut my hours': 'Me sancionaron, despidieron o redujeron mis horas', 'Required me to attend an anti-union meeting': 'Me obligaron a asistir a una reunión contra el sindicato', 'Something else': 'Otra cosa',
  'Share with the committee': 'Compartir con el comité', 'Shared with the committee.': 'Compartido con el comité.', 'Download my record': 'Descargar mi registro',
  'Time limit to file a charge: about {n} days left': 'Plazo para presentar una queja: quedan unos {n} días', 'Deadline to file may have passed. Ask soon.': 'Es posible que el plazo haya pasado. Consulta pronto.',
  'Time limits are general guidance, not legal advice. A lawyer or the labor board can tell you the exact deadline.': 'Los plazos son orientación general, no asesoría legal. Un abogado o la junta laboral pueden decirte el plazo exacto.',
  // trustee enrollment (most important screens)
  'Become a trustee for {union}': 'Conviértete en custodio de {union}',
  '1. Choose a passphrase': '1. Elige una frase de acceso', '2. Create and save your key file': '2. Crea y guarda tu archivo de llave', '3. Finish': '3. Terminar',
  'Create my key file': 'Crear mi archivo de llave', 'Finish enrollment': 'Terminar la inscripción', 'You are enrolled': 'Estás inscrito',
  'I saved my key file and my passphrase somewhere safe.': 'Guardé mi archivo de llave y mi frase de acceso en un lugar seguro.',
  // wizard
  'Where do you work?': '¿Dónde trabajas?', 'What will your union be called?': '¿Cómo se llamará tu sindicato?', 'Union name': 'Nombre del sindicato',
  'Who is your employer?': '¿Quién es tu empleador?', "Employer's legal name": 'Nombre legal del empleador', 'Who is in your group?': '¿Quiénes están en tu grupo?',
  'About how many people is that?': '¿Aproximadamente cuántas personas son?', 'Number of coworkers': 'Número de compañeros', 'Choose your trustees': 'Elige a tus custodios',
  'Create my campaign': 'Crear mi campaña', 'Your campaign is ready': 'Tu campaña está lista', 'Step {i} of {n}': 'Paso {i} de {n}',
  'Read the card your coworkers will sign': 'Lee la tarjeta que firmarán tus compañeros',
  // safety
  'Sign in': 'Iniciar sesión',
};
